// SURE İSİMLERİ LİSTESİ
export const SURE_ISIMLERI = [
  { id: 1, name: "Fâtiha", ayet: 7, anlami: "Açılış", juz: 1, page: 1 },
  { id: 2, name: "Bakara", ayet: 286, anlami: "İnek", juz: 1, page: 2 },
  { id: 3, name: "Âl-i İmrân", ayet: 200, anlami: "İmran Ailesi", juz: 3, page: 50 },
  { id: 4, name: "Nisâ", ayet: 176, anlami: "Kadınlar", juz: 4, page: 77 },
  { id: 5, name: "Mâide", ayet: 120, anlami: "Sofra", juz: 6, page: 106 },
  { id: 6, name: "En'âm", ayet: 165, anlami: "Hayvanlar", juz: 7, page: 128 },
  { id: 7, name: "A'râf", ayet: 206, anlami: "Yüksek Yerler", juz: 8, page: 151 },
  { id: 8, name: "Enfâl", ayet: 75, anlami: "Savaş Ganimetleri", juz: 9, page: 177 },
  { id: 9, name: "Tevbe", ayet: 129, anlami: "Tövbe", juz: 10, page: 187 },
  { id: 10, name: "Yûnus", ayet: 109, anlami: "Yunus Peygamber", juz: 11, page: 208 },
  { id: 11, name: "Hûd", ayet: 123, anlami: "Hud Peygamber", juz: 11, page: 221 },
  { id: 12, name: "Yûsuf", ayet: 111, anlami: "Yusuf Peygamber", juz: 12, page: 235 },
  { id: 13, name: "Ra'd", ayet: 43, anlami: "Gök Gürültüsü", juz: 13, page: 249 },
  { id: 14, name: "İbrahim", ayet: 52, anlami: "İbrahim Peygamber", juz: 13, page: 255 },
  { id: 15, name: "Hicr", ayet: 99, anlami: "Taşlı Yer", juz: 14, page: 262 },
  { id: 16, name: "Nahl", ayet: 128, anlami: "Bal Arısı", juz: 14, page: 267 },
  { id: 17, name: "İsrâ", ayet: 111, anlami: "Gece Yürüyüşü", juz: 15, page: 282 },
  { id: 18, name: "Kehf", ayet: 110, anlami: "Mağara", juz: 15, page: 293 },
  { id: 19, name: "Meryem", ayet: 98, anlami: "Hz. Meryem", juz: 16, page: 305 },
  { id: 20, name: "Tâhâ", ayet: 135, anlami: "Tâ-Hâ Harfleri", juz: 16, page: 312 },
  { id: 21, name: "Enbiyâ", ayet: 112, anlami: "Peygamberler", juz: 17, page: 322 },
  { id: 22, name: "Hac", ayet: 78, anlami: "Hac İbadeti", juz: 17, page: 332 },
  { id: 23, name: "Mü'minûn", ayet: 118, anlami: "Müminler", juz: 18, page: 342 },
  { id: 24, name: "Nûr", ayet: 64, anlami: "Işık", juz: 18, page: 350 },
  { id: 25, name: "Furkan", ayet: 77, anlami: "Doğruyu Yanlıştan Ayıran", juz: 18, page: 359 },
  { id: 26, name: "Şuarâ", ayet: 227, anlami: "Şairler", juz: 19, page: 367 },
  { id: 27, name: "Neml", ayet: 93, anlami: "Karınca", juz: 19, page: 377 },
  { id: 28, name: "Kasas", ayet: 88, anlami: "Kıssalar", juz: 20, page: 385 },
  { id: 29, name: "Ankebût", ayet: 69, anlami: "Örümcek", juz: 20, page: 396 },
  { id: 30, name: "Rûm", ayet: 60, anlami: "Romalılar", juz: 21, page: 404 },
  { id: 31, name: "Lokmân", ayet: 34, anlami: "Lokman Hekim", juz: 21, page: 411 },
  { id: 32, name: "Secde", ayet: 30, anlami: "Secde Etmek", juz: 21, page: 415 },
  { id: 33, name: "Ahzâb", ayet: 73, anlami: "Gruplar", juz: 21, page: 418 },
  { id: 34, name: "Sebe'", ayet: 54, anlami: "Sebe Halkı", juz: 22, page: 428 },
  { id: 35, name: "Fâtır", ayet: 45, anlami: "Yaratan", juz: 22, page: 434 },
  { id: 36, name: "Yâsîn", ayet: 83, anlami: "Yâ-Sîn Harfleri", juz: 22, page: 440 },
  { id: 37, name: "Sâffât", ayet: 182, anlami: "Sıra Sıra Dizenler", juz: 23, page: 446 },
  { id: 38, name: "Sâd", ayet: 88, anlami: "Sâd Harfi", juz: 23, page: 453 },
  { id: 39, name: "Zümer", ayet: 75, anlami: "Zümreler", juz: 23, page: 458 },
  { id: 40, name: "Mü'min", ayet: 85, anlami: "İnanan", juz: 24, page: 467 },
  { id: 41, name: "Fussilet", ayet: 54, anlami: "Genişçe Açıklanmış", juz: 24, page: 477 },
  { id: 42, name: "Şûrâ", ayet: 53, anlami: "Danışma", juz: 25, page: 483 },
  { id: 43, name: "Zuhruf", ayet: 89, anlami: "Süs", juz: 25, page: 489 },
  { id: 44, name: "Duhân", ayet: 59, anlami: "Duman", juz: 25, page: 496 },
  { id: 45, name: "Câsiye", ayet: 37, anlami: "Diz Çöken", juz: 25, page: 499 },
  { id: 46, name: "Ahkâf", ayet: 35, anlami: "Kum Tepeleri", juz: 26, page: 502 },
  { id: 47, name: "Muhammed", ayet: 38, anlami: "Hz. Muhammed", juz: 26, page: 507 },
  { id: 48, name: "Fetih", ayet: 29, anlami: "Zafer", juz: 26, page: 511 },
  { id: 49, name: "Hucurât", ayet: 18, anlami: "Odalar", juz: 26, page: 515 },
  { id: 50, name: "Kâf", ayet: 45, anlami: "Kâf Harfi", juz: 26, page: 518 },
  { id: 51, name: "Zâriyât", ayet: 60, anlami: "Ezip Savuranlar", juz: 26, page: 520 },
  { id: 52, name: "Tûr", ayet: 49, anlami: "Tur Dağı", juz: 27, page: 523 },
  { id: 53, name: "Necm", ayet: 62, anlami: "Yıldız", juz: 27, page: 526 },
  { id: 54, name: "Kamer", ayet: 55, anlami: "Ay", juz: 27, page: 528 },
  { id: 55, name: "Rahmân", ayet: 78, anlami: "Çok Merhametli", juz: 27, page: 531 },
  { id: 56, name: "Vâkıa", ayet: 96, anlami: "Olay (Kıyamet)", juz: 27, page: 534 },
  { id: 57, name: "Hadîd", ayet: 29, anlami: "Demir", juz: 27, page: 537 },
  { id: 58, name: "Mücâdele", ayet: 22, anlami: "Tartışma", juz: 28, page: 542 },
  { id: 59, name: "Haşr", ayet: 24, anlami: "Toplanma", juz: 28, page: 545 },
  { id: 60, name: "Mümtehine", ayet: 13, anlami: "Sınanan Kadın", juz: 28, page: 549 },
  { id: 61, name: "Saff", ayet: 14, anlami: "Sıra", juz: 28, page: 551 },
  { id: 62, name: "Cuma", ayet: 11, anlami: "Cuma Günü", juz: 28, page: 553 },
  { id: 63, name: "Münâfikûn", ayet: 11, anlami: "İkiyüzlüler", juz: 28, page: 554 },
  { id: 64, name: "Tegâbün", ayet: 18, anlami: "Aldanma", juz: 28, page: 556 },
  { id: 65, name: "Talâk", ayet: 12, anlami: "Boşanma", juz: 28, page: 558 },
  { id: 66, name: "Tahrîm", ayet: 12, anlami: "Haram Kılma", juz: 28, page: 560 },
  { id: 67, name: "Mülk", ayet: 30, anlami: "Hükümranlık", juz: 29, page: 562 },
  { id: 68, name: "Kalem", ayet: 52, anlami: "Kalem", juz: 29, page: 564 },
  { id: 69, name: "Hâkka", ayet: 52, anlami: "Gerçekleşecek Olan", juz: 29, page: 566 },
  { id: 70, name: "Meâric", ayet: 44, anlami: "Yükseliş Yolları", juz: 29, page: 568 },
  { id: 71, name: "Nûh", ayet: 28, anlami: "Nuh Peygamber", juz: 29, page: 570 },
  { id: 72, name: "Cin", ayet: 28, anlami: "Cinler", juz: 29, page: 572 },
  { id: 73, name: "Müzzemmil", ayet: 20, anlami: "Örtünüp Bürünen", juz: 29, page: 574 },
  { id: 74, name: "Müddessir", ayet: 56, anlami: "Gizlenen", juz: 29, page: 575 },
  { id: 75, name: "Kıyamet", ayet: 40, anlami: "Kıyamet Günü", juz: 29, page: 577 },
  { id: 76, name: "İnsan", ayet: 31, anlami: "İnsan", juz: 29, page: 578 },
  { id: 77, name: "Mürselât", ayet: 50, anlami: "Gönderilenler", juz: 29, page: 580 },
  { id: 78, name: "Nebe", ayet: 40, anlami: "Haber", juz: 30, page: 582 },
  { id: 79, name: "Nâziât", ayet: 46, anlami: "Söküp Çıkaranlar", juz: 30, page: 583 },
  { id: 80, name: "Abese", ayet: 42, anlami: "Yüzünü Ekşitti", juz: 30, page: 585 },
  { id: 81, name: "Tekvîr", ayet: 29, anlami: "Dürülme", juz: 30, page: 586 },
  { id: 82, name: "İnfitâr", ayet: 19, anlami: "Yarılma", juz: 30, page: 587 },
  { id: 83, name: "Mutaffifîn", ayet: 36, anlami: "Ölçüde Hile Yapanlar", juz: 30, page: 587 },
  { id: 84, name: "İnşikâk", ayet: 25, anlami: "Yarılma", juz: 30, page: 589 },
  { id: 85, name: "Burûc", ayet: 22, anlami: "Burçlar", juz: 30, page: 590 },
  { id: 86, name: "Târık", ayet: 17, anlami: "Gece Gelen", juz: 30, page: 591 },
  { id: 87, name: "A'lâ", ayet: 19, anlami: "En Yüce", juz: 30, page: 591 },
  { id: 88, name: "Gâşiye", ayet: 26, anlami: "Kaplayıp Bürüyen", juz: 30, page: 592 },
  { id: 89, name: "Fecr", ayet: 30, anlami: "Tan Yeri", juz: 30, page: 593 },
  { id: 90, name: "Beled", ayet: 20, anlami: "Şehir", juz: 30, page: 594 },
  { id: 91, name: "Şems", ayet: 15, anlami: "Güneş", juz: 30, page: 595 },
  { id: 92, name: "Leyl", ayet: 21, anlami: "Gece", juz: 30, page: 595 },
  { id: 93, name: "Duhâ", ayet: 11, anlami: "Kuşluk Vakti", juz: 30, page: 596 },
  { id: 94, name: "İnşirah", ayet: 8, anlami: "Ferahlamak", juz: 30, page: 596 },
  { id: 95, name: "Tîn", ayet: 8, anlami: "İncir", juz: 30, page: 597 },
  { id: 96, name: "Alak", ayet: 19, anlami: "Kan Pıhtısı", juz: 30, page: 597 },
  { id: 97, name: "Kadir", ayet: 5, anlami: "Kadir Gecesi", juz: 30, page: 598 },
  { id: 98, name: "Beyyine", ayet: 8, anlami: "Apaçık Delil", juz: 30, page: 598 },
  { id: 99, name: "Zilzâl", ayet: 8, anlami: "Deprem", juz: 30, page: 599 },
  { id: 100, name: "Âdiyât", ayet: 11, anlami: "Koşan Atlar", juz: 30, page: 599 },
  { id: 101, name: "Kâria", ayet: 11, anlami: "Kapı Çalan", juz: 30, page: 600 },
  { id: 102, name: "Tekâsür", ayet: 8, anlami: "Çoğaltma Yarışı", juz: 30, page: 600 },
  { id: 103, name: "Asr", ayet: 3, anlami: "Zaman", juz: 30, page: 601 },
  { id: 104, name: "Hümeze", ayet: 9, anlami: "Çekiştiren", juz: 30, page: 601 },
  { id: 105, name: "Fîl", ayet: 5, anlami: "Fil", juz: 30, page: 601 },
  { id: 106, name: "Kureyş", ayet: 4, anlami: "Kureyş Kabilesi", juz: 30, page: 602 },
  { id: 107, name: "Mâûn", ayet: 7, anlami: "Yardım", juz: 30, page: 602 },
  { id: 108, name: "Kevser", ayet: 3, anlami: "Bol Nimet", juz: 30, page: 602 },
  { id: 109, name: "Kâfirûn", ayet: 6, anlami: "İnkarcılar", juz: 30, page: 603 },
  { id: 110, name: "Nasr", ayet: 3, anlami: "Yardım", juz: 30, page: 603 },
  { id: 111, name: "Tebbet", ayet: 5, anlami: "Kurumasın", juz: 30, page: 603 },
  { id: 112, name: "İhlâs", ayet: 4, anlami: "Samimiyet", juz: 30, page: 604 },
  { id: 113, name: "Felâk", ayet: 5, anlami: "Sabah", juz: 30, page: 604 },
  { id: 114, name: "Nâs", ayet: 6, anlami: "İnsanlar", juz: 30, page: 604 }
];

// 50 TANE SEÇME DUA LİSTESİ
export const GUNLUK_DUALAR = [
  { id: 'd1', title: "Dünya ve Ahiret İyiliği", detail: "Rabbimiz! Bize dünyada da iyilik ver, ahirette de iyilik ver ve bizi ateş azabından koru.", source: "Bakara, 201" },
  { id: 'd2', title: "Allah Sevgisi", detail: "Allah'ım! Senin sevgini, seni sevenin sevgisini ve beni senin sevgine ulaştıracak ameli talep ediyorum.", source: "Tirmizî" },
  { id: 'd3', title: "Kalplerin Sabiti", detail: "Ey kalpleri çeviren Allah'ım! Kalbimi dinin üzerine sabit kıl.", source: "Tirmizî" },
  { id: 'd4', title: "Faydalı İlim", detail: "Allah'ım! Senden faydalı ilim, temiz rızık ve kabul olunan amel istiyorum.", source: "İbn Mâce" },
  { id: 'd5', title: "Salihler Zümresi", detail: "Rabbim! İlmimi artır ve beni salihler zümresine kat.", source: "Şuarâ, 83" },
  { id: 'd6', title: "Kapsamlı Dua", detail: "Allah'ım! Beni bağışla, bana merhamet et, bana hidayet ver, bana afiyet ver ve beni rızıklandır.", source: "Müslim" },
  { id: 'd7', title: "Şerlerden Sığınma", detail: "Allah'ım! Yaptığım ve yapmadığım şeylerin şerrinden sana sığınırım.", source: "Müslim" },
  { id: 'd8', title: "Affetmeyi Seversin", detail: "Allah'ım! Sen affedicisin, cömertsin, affetmeyi seversin; beni de affet.", source: "Tirmizî" },
  { id: 'd9', title: "Namazı Dosdoğru Kılmak", detail: "Rabbim! Beni ve soyumdan gelecekleri namazı dosdoğru kılanlardan eyle. Rabbimiz dualarımızı kabul buyur.", source: "İbrahim, 40" },
  { id: 'd10', title: "Rahmet ve Hidayet", detail: "Rabbimiz! Katından bize bir rahmet ver ve işimizde bize doğruyu göster.", source: "Kehf, 10" },
  { id: 'd11', title: "Zalimlerden Olmamak", detail: "Rabbimiz! Bizi zalimler topluluğu ile beraber bulundurma.", source: "A'râf, 47" },
  { id: 'd12', title: "Hata ve Unutma", detail: "Rabbimiz! Unutur veya hataya düşersek bizi sorumlu tutma.", source: "Bakara, 286" },
  { id: 'd13', title: "Göz Aydınlığı Eşler", detail: "Rabbimiz! Bize göz aydınlığı olacak eşler ve zürriyetler bağışla ve bizi takva sahiplerine önder kıl.", source: "Furkan, 74" },
  { id: 'd14', title: "Şükretmek", detail: "Rabbim! Bana ve ana-babama verdiğin nimete şükretmemi ve razı olacağın yararlı iş yapmamı temin et.", source: "Neml, 19" },
  { id: 'd15', title: "İlmimi Artır", detail: "Rabbim! Benim ilmimi artır.", source: "Tâhâ, 114" },
  { id: 'd16', title: "Göğüs Genişliği", detail: "Rabbim! Göğsümü genişlet, işimi kolaylaştır, dilimdeki düğümü çöz ki sözümü anlasınlar.", source: "Tâhâ, 25-28" },
  { id: 'd17', title: "Şeytanın Vesvesesi", detail: "Rabbim! Şeytanların kışkırtmalarından sana sığınırım.", source: "Mü'minûn, 97" },
  { id: 'd18', title: "Cehennem Azabı", detail: "Rabbimiz! Cehennem azabını üzerimizden sav. Doğrusu onun azabı gelip geçici değil, devamlıdır.", source: "Furkan, 65" },
  { id: 'd19', title: "Nurumuzu Tamamla", detail: "Rabbimiz! Nurumuzu tamamla, bizi bağışla; çünkü sen her şeye kadirsin.", source: "Tahrîm, 8" },
  { id: 'd20', title: "Yalnız Sana Güvendik", detail: "Rabbimiz! Ancak sana dayandık, sana yöneldik. Dönüş de ancak sanadır.", source: "Mümtehine, 4" },
  { id: 'd21', title: "Borç ve Tembellik", detail: "Allah'ım! Acizlikten, tembellikten, korkaklıktan, cimrilikten ve kabir azabından sana sığınırım.", source: "Müslim" },
  { id: 'd22', title: "Kötü Ahlak", detail: "Allah'ım! Kötü ahlaktan, nefsani arzulardan, kötü işlerden ve ayıp şeylerden sana sığınırım.", source: "Tirmizî" },
  { id: 'd23', title: "Yaratılış ve Ahlak", detail: "Allah'ım! Yaratılışımı güzel yaptığın gibi ahlakımı da güzelleştir.", source: "Ahmed b. Hanbel" },
  { id: 'd24', title: "Hidayet ve Takva", detail: "Allah'ım! Senden hidayet, takva, iffet ve gönül zenginliği istiyorum.", source: "Müslim" },
  { id: 'd25', title: "Gazap ve Rıza", detail: "Allah'ım! Gazabından rızana, cezandan affına sığınırım.", source: "Müslim" },
  { id: 'd26', title: "Kalp Katılığı", detail: "Allah'ım! Ürpermeyen kalpten, doymayan nefisten, fayda vermeyen ilimden ve kabul olunmayan duadan sana sığınırım.", source: "Tirmizî" },
  { id: 'd27', title: "Nimetin Zevali", detail: "Allah'ım! Nimetinin yok olmasından, afiyetinin değişmesinden, ansızın gelecek cezandan sana sığınırım.", source: "Müslim" },
  { id: 'd28', title: "Hayırlı Son", detail: "Allah'ım! Sonumuzu hayırlı eyle, işlerimizin sonucunu güzel eyle.", source: "Hadis-i Şerif" },
  { id: 'd29', title: "Sıkıntı Anı", detail: "La ilahe illallahü'l-azimü'l-halim. (Büyük ve Halim olan Allah'tan başka ilah yoktur.)", source: "Buhari" },
  { id: 'd30', title: "Borçtan Kurtulma", detail: "Allah'ım! Kederden ve hüzünden, acizlikten ve tembellikten sana sığınırım.", source: "Buhari" },
  { id: 'd31', title: "Geçim Sıkıntısı", detail: "Allah'ım! Beni helal rızkınla haramdan koru ve lütfunla beni senden başkasına muhtaç etme.", source: "Tirmizî" },
  { id: 'd32', title: "Dua-i İsm-i Azam", detail: "Ey Hayy ve Kayyum olan! Rahmetinle yardım istiyorum.", source: "Tirmizî" },
  { id: 'd33', title: "Hasta Duası", detail: "Bu hastalığı gider ey insanların Rabbi! Şifa ver, çünkü şifa verici sensin.", source: "Buhari" },
  { id: 'd34', title: "Yolculuk Duası", detail: "Allah'ım! Bu yolculuğumuzda senden iyilik ve takva, razı olacağın ameller istiyoruz.", source: "Müslim" },
  { id: 'd35', title: "Eve Girerken", detail: "Allah'ım! Senden girecek yerin hayrını ve çıkacak yerin hayrını istiyorum.", source: "Ebu Davud" },
  { id: 'd36', title: "İftira ve Haksızlık", detail: "Rabbim! Bana ve kardeşime mağfiret et, bizi rahmetinin içine al.", source: "A'râf, 151" },
  { id: 'd37', title: "Beni Utandırma", detail: "Rabbim! (İnsanların) diriltilecekleri gün beni utandırma.", source: "Şuarâ, 87" },
  { id: 'd38', title: "Şirkten Korunma", detail: "Allah'ım! Bilerek sana şirk koşmaktan sana sığınırım, bilmediklerimden dolayı da senden mağfiret dilerim.", source: "Ahmed b. Hanbel" },
  { id: 'd39', title: "Musibet Anı", detail: "Biz Allah'a aidiz ve şüphesiz O'na döneceğiz. Allah'ım! Bu musibetimden dolayı beni mükafatlandır.", source: "Müslim" },
  { id: 'd40', title: "Öfke Anı", detail: "Taşlanmış şeytandan Allah'a sığınırım.", source: "Buhari" },
  { id: 'd41', title: "Kadir Gecesi", detail: "Allah'ım! Sen affedicisin, ikram sahibisin, affetmeyi seversin; beni de affet.", source: "Tirmizî" },
  { id: 'd42', title: "Uyku Öncesi", detail: "Allah'ım! Senin isminle ölür ve dirilirim.", source: "Buhari" },
  { id: 'd43', title: "Uyanınca", detail: "Bizi öldürdükten sonra dirilten Allah'a hamdolsun. Dönüş ancak O'nadır.", source: "Buhari" },
  { id: 'd44', title: "Tuvalete Girerken", detail: "Allah'ım! Pislikten ve pis şeylerden (şeytanlardan) sana sığınırım.", source: "Buhari" },
  { id: 'd45', title: "Tuvaletten Çıkınca", detail: "Allah'ım! Senin affını dilerim. Benden eziyeti gideren ve bana afiyet veren Allah'a hamdolsun.", source: "İbn Mâce" },
  { id: 'd46', title: "Camiye Girerken", detail: "Allah'ım! Bana rahmet kapılarını aç.", source: "Müslim" },
  { id: 'd47', title: "Camiden Çıkarken", detail: "Allah'ım! Senden lütuf ve keremini istiyorum.", source: "Müslim" },
  { id: 'd48', title: "Ayna Duası", detail: "Allah'ım! Yaratılışımı güzel kıldığın gibi ahlakımı da güzelleştir.", source: "İbn Hibban" },
  { id: 'd49', title: "Yemek Duası", detail: "Bizi yediren, içiren ve Müslüman kılan Allah'a hamdolsun.", source: "Tirmizî" },
  { id: 'd50', title: "Tövbe Duası", detail: "Rabbim! Beni bağışla ve tövbemi kabul et. Şüphesiz sen tövbeleri çokça kabul eden ve merhamet edensin.", source: "Ebu Davud" }
];

// HADİS LİSTESİ
export const GUNLUK_HADISLER = [
  { text: "Kolaylaştırınız, zorlaştırmayınız; müjdeleyiniz, nefret ettirmeyiniz.", source: "Buhârî, İlim, 11" },
  { text: "Ameller niyetlere göredir. Herkes sadece niyetinin karşılığını alır.", source: "Buhârî, Bed'ü'l-Vahy, 1" },
  { text: "Sizin en hayırlınız, Kur'an'ı öğrenen ve öğretendir.", source: "Tirmizî, Fedâilü'l-Kur'ân, 15" },
  { text: "Güzel söz sadakadır.", source: "Buhârî, Edeb, 34" },
  { text: "Komşusu açken tok yatan bizden değildir.", source: "İbn Ebi Şeybe, Musannef" },
  { text: "Müslüman, elinden ve dilinden diğer Müslümanların emin olduğu kimsedir.", source: "Buhârî, Îmân, 4" },
  { text: "Kim Allah'a ve ahiret gününe iman ediyorsa, ya hayır söylesin ya da sussun.", source: "Buhârî, Edeb, 31" },
  { text: "Temizlik imanın yarısıdır.", source: "Müslim, Tahâret, 1" },
  { text: "İki günü eşit olan ziyandadır.", source: "Hadis-i Şerif" },
  { text: "Tebessüm sadakadır.", source: "Tirmizî, Birr, 36" },
  { text: "İnsanlara merhamet etmeyene Allah merhamet etmez.", source: "Müslim, Fedâil, 66" },
  { text: "Hiçbiriniz kendisi için istediğini kardeşi için de istemedikçe (tam) iman etmiş olmaz.", source: "Buhârî, Îmân, 7" },
  { text: "Cennet annelerin ayakları altındadır.", source: "Nesâî, Cihad, 6" },
  { text: "Veren el, alan elden üstündür.", source: "Buhârî, Zekât, 18" },
  { text: "Hasetten sakınınız! Çünkü ateşin odunu yiyip bitirdiği gibi haset de iyilikleri yer bitirir.", source: "Ebû Dâvûd, Edeb, 44" },
  { text: "Bizi aldatan bizden değildir.", source: "Müslim, Îmân, 164" },
  { text: "Allah sizin suretlerinize ve mallarınıza bakmaz, ancak kalplerinize ve amellerinize bakar.", source: "Müslim, Birr, 33" },
  { text: "İşçiye ücretini, alnının teri kurumadan veriniz.", source: "İbn Mâce, Ruhûn, 4" },
  { text: "Mümin, bir delikten iki defa ısırılmaz (Aynı hataya iki kez düşmez).", source: "Buhârî, Edeb, 83" },
  { text: "Kıyamet kopuyor olsa bile, elinizdeki fidanı dikiniz.", source: "Ahmed b. Hanbel, Müsned" },
  { text: "Güçlü kimse, güreşte rakibini yenen değil, öfke anında kendine hakim olandır.", source: "Buhârî, Edeb, 76" },
  { text: "Her dinin bir ahlakı vardır; İslam'ın ahlakı da hayâdır (utanma duygusu).", source: "İbn Mâce, Zühd, 17" },
  { text: "Sadaka malı eksiltmez.", source: "Müslim, Birr, 69" },
  { text: "Kim bir hayra vesile olursa, o hayrı yapan gibi sevap alır.", source: "Müslim, İmâre, 133" },
  { text: "Danışan pişman olmaz.", source: "Taberânî" },
  { text: "Merhamet etmeyene merhamet olunmaz.", source: "Buhârî, Edeb, 18" },
  { text: "Müminin mümin üzerindeki hakkı altıdır: Hastalandığında ziyaret eder, öldüğünde cenazesine katılır, davet ettiğinde icabet eder, selam verdiğinde selamını alır, aksırdığında 'yerhamükellah' der, yanında ve gıyabında onun iyiliğini ister.", source: "Müslim, Selam, 5" },
  { text: "Allah güzeldir, güzelliği sever.", source: "Müslim, Îmân, 147" },
  { text: "Zenginlik mal çokluğuyla değil, gönül tokluğuyladır.", source: "Buhârî, Rikak, 15" },
  { text: "Dua, müminin silahıdır.", source: "Ebû Ya’lâ, Müsned" },
  { text: "Kişi sevdiği ile beraberdir.", source: "Buhârî, Edeb, 96" },
  { text: "İlim öğrenmek, kadın-erkek her Müslümana farzdır.", source: "İbn Mâce, Mukaddime, 17" },
  { text: "Hiçbir baba, çocuğuna güzel ahlaktan daha kıymetli bir miras bırakmamıştır.", source: "Tirmizî, Birr, 33" },
  { text: "Yalan, rızkı azaltır.", source: "Hadis-i Şerif" },
  { text: "Hediyeleşiniz ki birbirinize olan sevginiz artsın.", source: "Buhârî, Edebü'l-Müfred" },
  { text: "Sizin en hayırlınız, ahlakı en güzel olanınızdır.", source: "Buhârî, Edeb, 38" },
  { text: "Mazlumun bedduasından sakın! Çünkü onunla Allah arasında perde yoktur.", source: "Buhârî, Zekât, 63" },
  { text: "Üç dua vardır ki kabul olunacağında şüphe yoktur: Mazlumun duası, misafirin duası ve babanın evladına duası.", source: "Tirmizî, Daavât, 48" },
  { text: "Beş şey gelmeden önce beş şeyin kıymetini bil: İhtiyarlığından önce gençliğinin, hastalığından önce sağlığının, fakirliğinden önce zenginliğinin, meşguliyetinden önce boş vaktinin ve ölümünden önce hayatının.", source: "Hâkim, Müstedrek" },
  { text: "İnsanların en hayırlısı, insanlara faydalı olandır.", source: "Buhârî, Mağâzî, 35" },
  { text: "Öfke şeytandandır.", source: "Ebû Dâvûd, Edeb, 47" },
  { text: "Kim susarsa kurtulur.", source: "Tirmizî, Kıyâmet, 50" },
  { text: "Allah'ın rızası, anne-babanın rızasındadır.", source: "Tirmizî, Birr, 3" },
  { text: "Dünya, müminin zindanı, kâfirin cennetidir.", source: "Müslim, Zühd, 1" },
  { text: "Kur'an'ı sesinizle güzelleştiriniz.", source: "Ebû Dâvûd, Vitir, 20" },
  { text: "Hayra anahtar, şerre kilit olunuz.", source: "İbn Mâce, Mukaddime, 19" }
];

// ESMAÜL HÜSNA LİSTESİ
export const ESMA_TR_LIST = [
  { number: 1, name: "Allah", arabic: "الله", meaning: "Eşi benzeri olmayan, bütün noksan sıfatlardan münezzeh tek ilah." },
  { number: 2, name: "Er-Rahman", arabic: "الرحمن", meaning: "Dünyada bütün mahlûkata merhamet eden, şefkat gösteren." },
  { number: 3, name: "Er-Rahim", arabic: "الرحيم", meaning: "Ahirette, sadece müminlere acıyan, merhamet eden." },
  { number: 4, name: "El-Melik", arabic: "الملك", meaning: "Mülkün, kâinatın sahibi, mülk ve saltanatı devamlı olan." },
  { number: 5, name: "El-Kuddüs", arabic: "القدوس", meaning: "Her noksanlıktan uzak ve her türlü takdise lâyık olan." },
  { number: 6, name: "Es-Selam", arabic: "السلام", meaning: "Her türlü tehlikelerden selamete çıkaran." },
  { number: 7, name: "El-Mü'min", arabic: "المؤمن", meaning: "Güven veren, emin kılan, koruyan." },
  { number: 8, name: "El-Müheymin", arabic: "المهيمن", meaning: "Her şeyi görüp gözeten, koruyan ve saklayan." },
  { number: 9, name: "El-Aziz", arabic: "العزيز", meaning: "İzzet sahibi, her şeye galip gelen, karşı gelinemeyen." },
  { number: 10, name: "El-Cebbar", arabic: "الجبار", meaning: "Azamet ve kudret sahibi. Dilediğini yapan ve yaptıran." },
  { number: 11, name: "El-Mütekebbir", arabic: "المتكبر", meaning: "Büyüklükte eşi, benzeri olmayan." },
  { number: 12, name: "El-Halık", arabic: "الخالق", meaning: "Yaratan, yoktan var eden." },
  { number: 13, name: "El-Bari", arabic: "البارئ", meaning: "Her şeyi kusursuz ve uyumlu yaratan." },
  { number: 14, name: "El-Musavvir", arabic: "المصور", meaning: "Varlıklara şekil veren." },
  { number: 15, name: "El-Gaffar", arabic: "الغفار", meaning: "Günahları örten ve çok mağfiret eden." },
  { number: 16, name: "El-Kahhar", arabic: "القهار", meaning: "Her şeye, her istediğini yapacak surette galip ve hakim olan." },
  { number: 17, name: "El-Vehhab", arabic: "الوهاب", meaning: "Karşılıksız hibeler veren, çok fazla ihsan eden." },
  { number: 18, name: "Er-Rezzak", arabic: "الرزاق", meaning: "Bütün mahlûkatın rızkını veren ve ihtiyacını karşılayan." },
  { number: 19, name: "El-Fettah", arabic: "الفتاح", meaning: "Her türlü müşkülleri açan ve kolaylaştıran, darlıktan kurtaran." },
  { number: 20, name: "El-Alim", arabic: "العليم", meaning: "Gizli açık, geçmiş, gelecek, her şeyi en ince detaylarına kadar bilen." },
  { number: 21, name: "El-Kabid", arabic: "القابض", meaning: "Dilediğine darlık veren, sıkan, daraltan." },
  { number: 22, name: "El-Basıt", arabic: "الباسط", meaning: "Dilediğine bolluk veren, açan, genişleten." },
  { number: 23, name: "El-Hafıd", arabic: "الخافض", meaning: "Dereceleri alçaltan." },
  { number: 24, name: "Er-Rafi", arabic: "الرافع", meaning: "Şeref verip yükselten." },
  { number: 25, name: "El-Muizz", arabic: "المعز", meaning: "Dilediğini aziz eden, izzet veren." },
  { number: 26, name: "El-Müzill", arabic: "المذل", meaning: "Dilediğini zillete düşüren." },
  { number: 27, name: "Es-Semi", arabic: "السميع", meaning: "Her şeyi en iyi işiten." },
  { number: 28, name: "El-Basir", arabic: "البصير", meaning: "Gizli açık, her şeyi en iyi gören." },
  { number: 29, name: "El-Hakem", arabic: "الحكيم", meaning: "Mutlak hakim, hakkı batıldan ayıran." },
  { number: 30, name: "El-Adl", arabic: "العدل", meaning: "Mutlak adil, çok adaletli." },
  { number: 31, name: "El-Latif", arabic: "اللطيف", meaning: "Lütuf ve ihsan sahibi, her şeye vakıf." },
  { number: 32, name: "El-Habir", arabic: "الخبير", meaning: "Her şeyden haberdar, gizli aşikâr her şeyi bilen." },
  { number: 33, name: "El-Halim", arabic: "الحليم", meaning: "Ceza vermede acele etmeyen, yumuşak davranan." },
  { number: 34, name: "El-Azim", arabic: "العظيم", meaning: "Büyüklükte benzeri olmayan, pek yüce." },
  { number: 35, name: "El-Gafur", arabic: "الغفور", meaning: "Affı, mağfireti bol." },
  { number: 36, name: "Eş-Şekur", arabic: "الشكور", meaning: "Az amele, çok sevap veren." },
  { number: 37, name: "El-Aliyy", arabic: "العلي", meaning: "Yüceler yücesi, çok yüce." },
  { number: 38, name: "El-Kebir", arabic: "الكبير", meaning: "Büyüklükte benzeri olmayan, pek büyük." },
  { number: 39, name: "El-Hafiz", arabic: "الحفيظ", meaning: "Her şeyi koruyucu olan." },
  { number: 40, name: "El-Mukit", arabic: "المقيت", meaning: "Her yaratılmışın rızkını, gıdasını veren, tayin eden." },
  { number: 41, name: "El-Hasib", arabic: "الحسيب", meaning: "Kulların hesabını en iyi gören." },
  { number: 42, name: "El-Celil", arabic: "الجليل", meaning: "Celal ve azamet sahibi." },
  { number: 43, name: "El-Kerim", arabic: "الكريم", meaning: "Keremi, lütuf ve ihsanı bol, karşılıksız veren." },
  { number: 44, name: "Er-Rakib", arabic: "الرقيب", meaning: "Her varlığı, her işi her an görüp, gözeten, kontrolü altında tutan." },
  { number: 45, name: "El-Mucib", arabic: "المجيب", meaning: "Duaları, istekleri kabul eden." },
  { number: 46, name: "El-Vasi", arabic: "الواسع", meaning: "Rahmet, kudret ve ilmi ile her şeyi ihata eden." },
  { number: 47, name: "El-Hakim", arabic: "الحكيم", meaning: "Her işi hikmetli, her şeyi hikmetle yaratan." },
  { number: 48, name: "El-Vedud", arabic: "الودود", meaning: "Kullarını en çok seven, sevilmeye en çok layık olan." },
  { number: 49, name: "El-Mecid", arabic: "المجيد", meaning: "Her türlü övgüye layık bulunan." },
  { number: 50, name: "El-Bais", arabic: "الباعث", meaning: "Ölüleri dirilten." },
  { number: 51, name: "Eş-Şekur", arabic: "الشكور", meaning: "Az amele, çok sevap veren." },
  { number: 52, name: "El-Hakk", arabic: "الحق", meaning: "Varlığı hiç değişmeden duran. Var olan, hakkı ortaya çıkaran." },
  { number: 53, name: "El-Vekil", arabic: "الوكيل", meaning: "Kendisine tevekkül edenlerin işlerini en iyi neticeye ulaştıran." },
  { number: 54, name: "El-Kaviyy", arabic: "القوي", meaning: "Kudreti en üstün ve hiç azalmayan." },
  { number: 55, name: "El-Metin", arabic: "المتين", meaning: "Kuvvet ve kudret kaynağı, pek güçlü." },
  { number: 56, name: "El-Veliyy", arabic: "الولي", meaning: "İnananların dostu, onları sevip yardım eden." },
  { number: 57, name: "El-Hamid", arabic: "الحميد", meaning: "Her türlü hamd ve senaya layık olan." },
  { number: 58, name: "El-Muhsi", arabic: "المحصي", meaning: "Yarattığı ve yaratacağı bütün varlıkların sayısını bilen." },
  { number: 59, name: "El-Mubdi", arabic: "المبدئ", meaning: "Maddesiz, örneksiz yaratan." },
  { number: 60, name: "El-Muid", arabic: "المعيد", meaning: "Yarattıklarını yok edip, sonra tekrar diriltecek olan." },
  { number: 61, name: "El-Muhyi", arabic: "المحيي", meaning: "İhya eden, dirilten, can veren." },
  { number: 62, name: "El-Mumit", arabic: "المميت", meaning: "Her canlıya ölümü tattıran." },
  { number: 63, name: "El-Hayy", arabic: "الحي", meaning: "Ezeli ve ebedi hayat sahibi." },
  { number: 64, name: "El-Kayyum", arabic: "القيوم", meaning: "Varlıkları diri tutan, zatı ile kaim olan." },
  { number: 65, name: "El-Vacid", arabic: "الواجد", meaning: "Kendisinden hiçbir şey gizli kalmayan, istediğini, istediği vakit bulan." },
  { number: 66, name: "El-Macid", arabic: "الماجد", meaning: "Kadri ve şanı büyük, keremi bol." },
  { number: 67, name: "El-Vahid", arabic: "الواحد", meaning: "Zat, sıfat ve fiillerinde benzeri ve ortağı olmayan, tek." },
  { number: 68, name: "Es-Samed", arabic: "الصمد", meaning: "Hiçbir şeye ihtiyacı olmayan, herkesin muhtaç olduğu." },
  { number: 69, name: "El-Kadir", arabic: "القادر", meaning: "Dilediğini dilediği gibi yaratmaya muktedir olan." },
  { number: 70, name: "El-Muktedir", arabic: "المقتدر", meaning: "Dilediği gibi tasarruf eden, her şeyi kolayca yaratan kudret sahibi." },
  { number: 71, name: "El-Mukaddim", arabic: "المقدم", meaning: "Dilediğini, öne alan, yükselten." },
  { number: 72, name: "El-Muahhir", arabic: "المؤخر", meaning: "Dilediğini sona bırakan, erteleyen, alçaltan." },
  { number: 73, name: "El-Evvel", arabic: "الأول", meaning: "Ezeli olan, varlığının başlangıcı olmayan." },
  { number: 74, name: "El-Ahir", arabic: "الآخر", meaning: "Ebedi olan, varlığının sonu olmayan." },
  { number: 75, name: "El-Zahir", arabic: "الظاهر", meaning: "Yarattıkları ile varlığı açık, aşikâr olan." },
  { number: 76, name: "El-Batın", arabic: "الباطن", meaning: "Aklın tasavvurundan gizli olan." },
  { number: 77, name: "El-Vali", arabic: "الوالي", meaning: "Bütün kâinatı idare eden." },
  { number: 78, name: "El-Müteali", arabic: "المتعالي", meaning: "Son derece yüce olan." },
  { number: 79, name: "El-Berr", arabic: "البر", meaning: "İyilik ve ihsanı bol, iyilik yapan." },
  { number: 80, name: "Et-Tevvab", arabic: "التواب", meaning: "Tövbeleri kabul edip, günahları bağışlayan." },
  { number: 81, name: "El-Müntekim", arabic: "المنتقم", meaning: "Asilerin, zalimlerin cezasını veren." },
  { number: 82, name: "El-Afuvv", arabic: "العفو", meaning: "Affedici, günahları silen." },
  { number: 83, name: "Er-Rauf", arabic: "الرؤوف", meaning: "Çok lütufkâr, çok esirgeyen." },
  { number: 84, name: "Malik-ül Mülk", arabic: "مالك الملك", meaning: "Mülkün, her varlığın sahibi." },
  { number: 85, name: "Zül-Celali vel İkram", arabic: "ذو الجلال والإكرام", meaning: "Celal, azamet ve pek büyük ikram sahibi." },
  { number: 86, name: "El-Muksit", arabic: "المقسط", meaning: "Her işi birbirine uygun yapan." },
  { number: 87, name: "El-Cami", arabic: "الجامع", meaning: "Mahşerde her mahlûkatı bir araya toplayan." },
  { number: 88, name: "El-Ganiyy", arabic: "الغني", meaning: "Her türlü zenginlik sahibi, ihtiyacı olmayan." },
  { number: 89, name: "El-Mugni", arabic: "المغني", meaning: "Müstağni kılan, ihtiyaç gideren, zengin eden." },
  { number: 90, name: "El-Mani", arabic: "المانع", meaning: "Bir şeyin meydana gelmesine izin vermeyen, engelleyen." },
  { number: 91, name: "Ed-Darr", arabic: "الضار", meaning: "Elem, zarar verenleri yaratan." },
  { number: 92, name: "En-Nafi", arabic: "النافع", meaning: "Fayda veren şeyleri yaratan." },
  { number: 93, name: "En-Nur", arabic: "النور", meaning: "Alemleri nurlandıran, dilediğine nur veren." },
  { number: 94, name: "El-Hadi", arabic: "الهادي", meaning: "Hidayet veren." },
  { number: 95, name: "El-Bedi", arabic: "البديع", meaning: "Eşi ve benzeri olmayan güzellikler yaratan." },
  { number: 96, name: "El-Baki", arabic: "الباقي", meaning: "Varlığının sonu olmayan, ebedi olan." },
  { number: 97, name: "El-Varis", arabic: "الوارث", meaning: "Her şeyin asıl sahibi olan." },
  { number: 98, name: "Er-Reşid", arabic: "الرشيد", meaning: "İrşada muhtaç olmayan, doğru yolu gösteren." },
  { number: 99, name: "Es-Sabur", arabic: "الصبور", meaning: "Ceza vermede acele etmeyen." }
];