// src/database/quizQuestions.js

export const localQuestions = [
  // --- KUR'AN-I KERİM ---
  { question: "Kur'an-ı Kerim'in ilk inen suresi hangisidir?", options: ["Fatiha Suresi", "Alak Suresi", "Bakara Suresi", "İhlas Suresi"], answerIndex: 1 },
  { question: "Kur'an-ı Kerim'in en uzun suresi hangisidir?", options: ["Yasin Suresi", "Bakara Suresi", "Al-i İmran Suresi", "Nisa Suresi"], answerIndex: 1 },
  { question: "Kur'an-ı Kerim'in en kısa suresi hangisidir?", options: ["Kevser Suresi", "İhlas Suresi", "Asr Suresi", "Nas Suresi"], answerIndex: 0 },
  { question: "Kur'an-ı Kerim kaç cüzden oluşmaktadır?", options: ["20", "30", "40", "114"], answerIndex: 1 },
  { question: "Besmele çekilmeyen tek sure hangisidir?", options: ["Tevbe Suresi", "Yasin Suresi", "Mülk Suresi", "Fetih Suresi"], answerIndex: 0 },
  { question: "Kur'an-ı Kerim'in kalbi olarak bilinen sure hangisidir?", options: ["Rahman Suresi", "Tebareke Suresi", "Yasin Suresi", "Vakıa Suresi"], answerIndex: 2 },
  { question: "İki defa besmele geçen sure hangisidir?", options: ["Neml Suresi", "Bakara Suresi", "Kehf Suresi", "İsra Suresi"], answerIndex: 0 },
  { question: "Ayet-el Kürsi hangi surenin içindedir?", options: ["Fatiha", "Bakara", "Yasin", "İhlas"], answerIndex: 1 },
  { question: "Kur'an-ı Kerim'de adı geçen tek kadın kimdir?", options: ["Hz. Hatice", "Hz. Fatıma", "Hz. Meryem", "Hz. Ayşe"], answerIndex: 2 },
  { question: "Kur'an'da kaç peygamberin ismi geçmektedir?", options: ["25", "28", "33", "99"], answerIndex: 0 },

  // --- SİYER (HZ. MUHAMMED'İN HAYATI) ---
  { question: "Peygamber Efendimiz (S.A.V) hangi şehirde doğmuştur?", options: ["Medine", "Kudüs", "Mekke", "Taif"], answerIndex: 2 },
  { question: "Peygamberimizin sütannesinin adı nedir?", options: ["Amine", "Halime", "Ümmü Eymen", "Fatıma"], answerIndex: 1 },
  { question: "Peygamber Efendimize ilk vahiy nerede gelmiştir?", options: ["Sevr Mağarası", "Hira Mağarası", "Kabe", "Mescid-i Nebevi"], answerIndex: 1 },
  { question: "Peygamberimizin Mekke'den Medine'ye göç etmesine ne denir?", options: ["Hicret", "İsra", "Miraç", "Cihat"], answerIndex: 0 },
  { question: "Peygamberimizin katıldığı ilk savaş hangisidir?", options: ["Uhud", "Hendek", "Mute", "Bedir"], answerIndex: 3 },
  { question: "Peygamberimizin vefat ettiği yıl hangisidir?", options: ["622", "632", "610", "630"], answerIndex: 1 },
  { question: "Peygamberimizin 'Gözümün nuru' dediği ibadet hangisidir?", options: ["Oruç", "Zekat", "Namaz", "Sadaka"], answerIndex: 2 },
  { question: "Hicret sırasında Peygamberimiz ile Sevr Mağarası'nda saklanan sahabi kimdir?", options: ["Hz. Ömer", "Hz. Ali", "Hz. Ebu Bekir", "Hz. Osman"], answerIndex: 2 },
  { question: "Peygamberimizin soyu hangi çocuğu üzerinden devam etmiştir?", options: ["Hz. Fatıma", "Hz. Zeynep", "Hz. Rukiye", "Hz. Ümmü Gülsüm"], answerIndex: 0 },
  { question: "Müslümanların ilk kıblesi neresidir?", options: ["Kabe", "Mescid-i Aksa", "Mescid-i Nebevi", "Kuba Mescidi"], answerIndex: 1 },

  // --- FIKIH VE İBADET ---
  { question: "İslam'ın şartı kaçtır?", options: ["4", "5", "6", "7"], answerIndex: 1 },
  { question: "Hangisi abdestin farzlarından biri değildir?", options: ["Yüzü yıkamak", "Ağza su vermek", "Kolları yıkamak", "Ayakları yıkamak"], answerIndex: 1 },
  { question: "Günde kaç vakit farz namaz vardır?", options: ["3", "4", "5", "6"], answerIndex: 2 },
  { question: "Zekat verebilmek için sahip olunması gereken asgari zenginlik ölçüsüne ne denir?", options: ["Fıtır", "Nisap", "Sadaka", "Öşür"], answerIndex: 1 },
  { question: "Ramazan ayında yatsı namazından sonra kılınan sünnet namaz hangisidir?", options: ["Teheccüd", "Evvabin", "Teravih", "İşrak"], answerIndex: 2 },
  { question: "Su bulunmadığı durumlarda toprakla alınan abdeste ne denir?", options: ["Teyemmüm", "Gusül", "Taharet", "Boy Abdesti"], answerIndex: 0 },
  { question: "Hac ibadeti sırasında Kabe'nin etrafında 7 kez dönmeye ne ad verilir?", options: ["Say", "Vakfe", "Tavaf", "İhram"], answerIndex: 2 },
  { question: "Cuma namazı kimlere farzdır?", options: ["Tüm Müslümanlara", "Akıllı ve ergenlik çağına girmiş hür erkeklere", "Sadece yaşlılara", "Kadın ve erkek herkese"], answerIndex: 1 },
  { question: "Hangisi namazı bozan durumlardan biridir?", options: ["Gülümsemek", "Esnemek", "Konuşmak", "Gözleri kapatmak"], answerIndex: 2 },
  { question: "Dinen zengin sayılanların Kurban Bayramı'nda kestiği kurbana ne denir?", options: ["Akika", "Adak", "Şükür", "Udhiyye (Kurban)"], answerIndex: 3 },

  // --- AKAİD (İMANIN ŞARTLARI VE MELEKLER) ---
  { question: "Aşağıdakilerden hangisi imanın şartlarından biri değildir?", options: ["Meleklere İman", "Zekat Vermek", "Kitaplara İman", "Ahirete İman"], answerIndex: 1 },
  { question: "Vahiy getirmekle görevli melek kimdir?", options: ["Mikail", "İsrafil", "Cebrail", "Azrail"], answerIndex: 2 },
  { question: "Doğa olaylarını ve rızıkları yönetmekle görevli melek kimdir?", options: ["Mikail", "İsrafil", "Kiramen Katibin", "Münker ve Nekir"], answerIndex: 0 },
  { question: "Kıyamet koptuğunda Sûr'a üfleyecek olan melek kimdir?", options: ["Cebrail", "İsrafil", "Azrail", "Mikail"], answerIndex: 1 },
  { question: "İnsanın sağ ve sol omzunda sevap ve günahları yazan meleklerin adı nedir?", options: ["Kiramen Katibin", "Hafaza", "Münker ve Nekir", "Hamele-i Arş"], answerIndex: 0 },
  { question: "Kabirde ilk sorguyu yapacak olan melekler kimlerdir?", options: ["Hafaza", "Kiramen Katibin", "Münker ve Nekir", "Rıdvan"], answerIndex: 2 },
  { question: "Kendisine Tevrat indirilen peygamber kimdir?", options: ["Hz. Davud", "Hz. İsa", "Hz. Musa", "Hz. İbrahim"], answerIndex: 2 },
  { question: "Kendisine Zebur indirilen peygamber kimdir?", options: ["Hz. Davud", "Hz. Musa", "Hz. İsa", "Hz. Nuh"], answerIndex: 0 },
  { question: "Hangi peygamber ateşe atılmış ancak ateş onu yakmamıştır?", options: ["Hz. İsa", "Hz. İbrahim", "Hz. Musa", "Hz. Nuh"], answerIndex: 1 },
  { question: "Babasız olarak dünyaya gelen peygamber kimdir?", options: ["Hz. Adem", "Hz. Yahya", "Hz. İsa", "Hz. İsmail"], answerIndex: 2 },

  // --- İSLAM TARİHİ VE SAHABELER ---
  { question: "İlk Müslüman olan kadın kimdir?", options: ["Hz. Ayşe", "Hz. Sümeyye", "Hz. Hatice", "Hz. Fatıma"], answerIndex: 2 },
  { question: "İslam'da ilk ezanı okuyan sahabi kimdir?", options: ["Hz. Ali", "Hz. Ömer", "Bilal-i Habeşi", "Hz. Hamza"], answerIndex: 2 },
  { question: "İlk halife kimdir?", options: ["Hz. Ömer", "Hz. Ali", "Hz. Osman", "Hz. Ebu Bekir"], answerIndex: 3 },
  { question: "Kur'an-ı Kerim hangi halife döneminde kitap (Mushaf) haline getirilmiştir?", options: ["Hz. Ebu Bekir", "Hz. Ömer", "Hz. Osman", "Hz. Ali"], answerIndex: 0 },
  { question: "Kur'an-ı Kerim hangi halife döneminde çoğaltılmıştır?", options: ["Hz. Ebu Bekir", "Hz. Ömer", "Hz. Osman", "Hz. Ali"], answerIndex: 2 },
  { question: "Peygamberimizin 'İlim şehrinin kapısıdır' dediği sahabi kimdir?", options: ["Hz. Ebu Bekir", "Hz. Ömer", "Hz. Osman", "Hz. Ali"], answerIndex: 3 },
  { question: "İslam'ın ilk şehidi olan kadın sahabi kimdir?", options: ["Hz. Hatice", "Hz. Sümeyye", "Hz. Asiye", "Hz. Zeynep"], answerIndex: 1 },
  { question: "Mekke'nin fethi hangi yılda gerçekleşmiştir?", options: ["622", "624", "628", "630"], answerIndex: 3 },
  { question: "Peygamberimizi Medine'de evinde ilk misafir eden sahabi kimdir?", options: ["Halid bin Velid", "Eyyüb el-Ensari", "Mus'ab bin Umeyr", "Zeyd bin Harise"], answerIndex: 1 },
  { question: "Uhud Savaşı'nda şehit düşen ve 'Şehitlerin Efendisi' olarak bilinen sahabi kimdir?", options: ["Hz. Ali", "Hz. Ömer", "Hz. Hamza", "Hz. Abbas"], answerIndex: 2 },
  { question: "Kur'an-ı Kerim kaç yılda parça parça indirilmiştir?", options: ["20", "23", "25", "40"], answerIndex: 1 },
{ question: "Tevbe Suresi'nin başında aşağıdakilerden hangisi bulunmaz?", options: ["Salavat", "Besmele", "Hamd", "Tekbir"], answerIndex: 1 },
{ question: "Kur'an-ı Kerim'de ismi açıkça geçen tek sahabi kimdir?", options: ["Hz. Ebu Bekir", "Hz. Ali", "Zeyd bin Harise", "Hz. Ömer"], answerIndex: 2 },
{ question: "Kur'an-ı Kerim'de ismi en çok geçen peygamber kimdir?", options: ["Hz. Muhammed", "Hz. İbrahim", "Hz. İsa", "Hz. Musa"], answerIndex: 3 },
{ question: "Fatiha Suresi'nin kelime anlamı nedir?", options: ["Açılış, Başlangıç", "Kurtuluş", "Barış", "Son"], answerIndex: 0 },
{ question: "Kur'an-ı Kerim hangi gecede indirilmeye başlanmıştır?", options: ["Berat Gecesi", "Miraç Gecesi", "Kadir Gecesi", "Regaip Gecesi"], answerIndex: 2 },
{ question: "Kur'an-ı Kerim'de 'Bin aydan daha hayırlıdır' diye bahsedilen gece hangisidir?", options: ["Berat Gecesi", "Kadir Gecesi", "Miraç Gecesi", "Mevlid Gecesi"], answerIndex: 1 },
{ question: "Kur'an-ı Kerim'in ilk emri nedir?", options: ["Yaz", "Dinle", "Oku", "Söyle"], answerIndex: 2 },
{ question: "Peygamberimize ilk vahiy nerede gelmiştir?", options: ["Sevr Mağarası", "Hira Mağarası", "Uhud Dağı", "Arafat"], answerIndex: 1 },
{ question: "'Muhakkak ki biz onu Kadir gecesinde indirdik' ayeti ile başlayan sure hangisidir?", options: ["Kadir Suresi", "Alak Suresi", "Bakara Suresi", "İhlas Suresi"], answerIndex: 0 },
{ question: "Hangi sure Kur'an'ın üçte birine denk kabul edilir?", options: ["Fatiha Suresi", "İhlas Suresi", "Felak Suresi", "Nas Suresi"], answerIndex: 1 },
{ question: "Kur'an-ı Kerim'de toplam kaç sure vardır?", options: ["110", "112", "114", "120"], answerIndex: 2 },
{ question: "Peygamber Efendimizin (S.A.V) babasının adı nedir?", options: ["Abdülmuttalip", "Ebu Talip", "Abdullah", "Hamza"], answerIndex: 2 },
{ question: "Peygamber Efendimizin (S.A.V) annesinin adı nedir?", options: ["Amine", "Halime", "Hatice", "Fatıma"], answerIndex: 0 },
{ question: "Peygamber Efendimiz (S.A.V) kaç yılında doğmuştur?", options: ["571", "610", "622", "632"], answerIndex: 0 },
{ question: "Peygamberimize 'Muhammed' ismini kim vermiştir?", options: ["Ebu Talip", "Abdullah", "Abdülmuttalip", "Amine"], answerIndex: 2 },
{ question: "Peygamber Efendimizin (S.A.V) ilk eşi kimdir?", options: ["Hz. Aişe", "Hz. Hatice", "Hz. Hafsa", "Hz. Sevde"], answerIndex: 1 },
{ question: "Hz. Muhammed'e (S.A.V) peygamberlik görevi kaç yaşında verilmiştir?", options: ["35", "40", "50", "63"], answerIndex: 1 },
{ question: "Peygamber Efendimizin (S.A.V) Veda Haccı hangi yılda gerçekleşmiştir?", options: ["622", "630", "632", "634"], answerIndex: 2 },
{ question: "Müslümanların Mekkeli müşriklerle yaptığı ilk savaş hangisidir?", options: ["Uhud Savaşı", "Hendek Savaşı", "Mute Savaşı", "Bedir Savaşı"], answerIndex: 3 },
{ question: "Peygamber Efendimizin (S.A.V) kabri hangi şehirdedir?", options: ["Mekke", "Medine", "Kudüs", "Taif"], answerIndex: 1 },
{ question: "Peygamberimizin kabrinin bulunduğu tertemiz bahçe anlamına gelen yerin adı nedir?", options: ["Cennet-ül Baki", "Mescid-i Aksa", "Ravza-i Mutahhara", "Kabe"], answerIndex: 2 },
{ question: "Müslümanlar ile Müşrikler arasındaki Hudeybiye Antlaşması kaç yılında imzalanmıştır?", options: ["622", "624", "628", "630"], answerIndex: 2 },
{ question: "Peygamber Efendimizin (S.A.V) bizzat katıldığı son gazve (savaş) hangisidir?", options: ["Mute Gazvesi", "Huneyn Gazvesi", "Tebük Gazvesi", "Hayber'in Fethi"], answerIndex: 2 },
{ question: "Peygamberimiz hicret ederken Sevr Mağarası'nda yanında hangi sahabi vardı?", options: ["Hz. Ali", "Hz. Ömer", "Hz. Ebu Bekir", "Hz. Osman"], answerIndex: 2 },
{ question: "Yatsı namazının farzı kaç rekattır?", options: ["2", "3", "4", "10"], answerIndex: 2 },
{ question: "Akşam namazının farzı kaç rekattır?", options: ["2", "3", "4", "5"], answerIndex: 1 },
{ question: "Cemaatle kılınması farz-ı ayın olan haftalık namaz hangisidir?", options: ["Bayram Namazı", "Cuma Namazı", "Teravih Namazı", "Cenaze Namazı"], answerIndex: 1 },
{ question: "Fitre (Fıtır sadakası) hangi ayda verilir?", options: ["Muharrem", "Recep", "Şaban", "Ramazan"], answerIndex: 3 },
{ question: "Aşağıdakilerden hangisine zekat verilmez?", options: ["Fakirlere", "Borçlulara", "Anne ve Babaya", "Yolda kalmışlara"], answerIndex: 2 },
{ question: "Hac ibadeti hicri takvime göre hangi ayda yapılır?", options: ["Ramazan", "Muharrem", "Şevval", "Zilhicce"], answerIndex: 3 },
{ question: "Haccın farzı kaçtır?", options: ["2", "3", "4", "5"], answerIndex: 1 },
{ question: "Hacda Kabe'nin etrafında bir kez dönmeye ne ad verilir?", options: ["Tavaf", "Say", "Vakfe", "Şavt"], answerIndex: 3 },
{ question: "Oruca başlama vaktine ne denir?", options: ["İftar", "İmsak", "Sahur", "Teravih"], answerIndex: 1 },
{ question: "Namazda ayakta durmaya ne ad verilir?", options: ["Kıraat", "Rükû", "Secde", "Kıyam"], answerIndex: 3 },
{ question: "Namazda ayaktayken Kur'an-ı Kerim okumaya ne ad verilir?", options: ["Kıyam", "Kıraat", "Secde", "İftitah tekbiri"], answerIndex: 1 },
{ question: "Yolculuğa çıkan birinin dört rekatlı farz namazları iki rekat kılmasına ne ad verilir?", options: ["Cem", "Seferi (Kasr)", "Kaza", "Nafile"], answerIndex: 1 },
{ question: "Nisap miktarı malın üzerinden ne kadar süre geçince zekat farz olur?", options: ["1 Ay", "6 Ay", "1 Kameri Yıl", "2 Yıl"], answerIndex: 2 },
{ question: "Adaletiyle meşhur olan İslam'ın 2. Halifesi kimdir?", options: ["Hz. Ebu Bekir", "Hz. Ali", "Hz. Ömer", "Hz. Osman"], answerIndex: 2 },
{ question: "Kur'an-ı Kerim'i kitap (mushaf) haline getiren heyetin başkanı kimdir?", options: ["Hz. Ali", "Zeyd bin Sabit", "Abdullah bin Mesud", "Hz. Osman"], answerIndex: 1 },
{ question: "Peygamberimiz tarafından 'Allah'ın Kılıcı' (Seyfullah) lakabı verilen komutan kimdir?", options: ["Hz. Hamza", "Halid bin Velid", "Tarık bin Ziyad", "Ebu Ubeyde bin Cerrah"], answerIndex: 1 },
{ question: "Meleklerin bile kendisinden haya ettiği, hayasıyla meşhur 3. halife kimdir?", options: ["Hz. Ebu Bekir", "Hz. Ömer", "Hz. Ali", "Hz. Osman"], answerIndex: 3 },
{ question: "Hz. Muhammed'in (S.A.V) halası olup, Hendek savaşında kahramanca mücadele eden kadın sahabi kimdir?", options: ["Hz. Fatıma", "Hz. Aişe", "Hz. Safiyye", "Hz. Sümeyye"], answerIndex: 2 },
{ question: "İlk İslam donanmasını kurarak deniz seferlerini başlatan halife kimdir?", options: ["Hz. Ebu Bekir", "Hz. Ömer", "Hz. Osman", "Muaviye"], answerIndex: 2 },
{ question: "Hendek Savaşı'nda şehrin etrafına hendek kazma fikrini veren İranlı sahabi kimdir?", options: ["Ammar bin Yasir", "Bilal-i Habeşi", "Selman-ı Farisi", "Hz. Ali"], answerIndex: 2 },
{ question: "Taif yolculuğunda Peygamberimizi atılan taşlardan korumak için kendi vücudunu siper eden sahabi kimdir?", options: ["Hz. Ebu Bekir", "Zeyd bin Harise", "Hz. Ali", "Hz. Hamza"], answerIndex: 1 },
{ question: "Uhud Savaşı'nda okçular tepesine yerleştirilen okçuların komutanı kimdir?", options: ["Hz. Hamza", "Mus'ab bin Umeyr", "Halid bin Velid", "Abdullah bin Cübeyr"], answerIndex: 3 },
{ question: "Mescid-i Nebevi inşa edilirken Peygamberimizi evinde 7 ay misafir eden sahabi kimdir?", options: ["Mus'ab bin Umeyr", "Ebu Eyyub el-Ensari", "Hz. Ebu Bekir", "Hz. Osman"], answerIndex: 1 },
{ question: "Habeşistan'a yapılan ilk hicrette kafileye başkanlık eden ve Necaşi'nin huzurunda konuşan sahabi kimdir?", options: ["Hz. Ömer", "Hz. Osman", "Cafer bin Ebu Talip", "Hz. Ali"], answerIndex: 2 },
{ question: "Peygamberimizin 'Her peygamberin bir havarisi vardır, benim havarim de odur' dediği sahabi kimdir?", options: ["Talha bin Ubeydullah", "Zübeyr bin Avvam", "Sad bin Ebi Vakkas", "Said bin Zeyd"], answerIndex: 1 },
{ question: "Kur'an-ı Kerim'de 'Besmele' ile başlamayan tek sure hangisidir?", options: ["Tevbe Suresi", "Enfal Suresi", "Yunus Suresi", "Nahl Suresi"], answerIndex: 0 },
{ question: "Kur'an-ı Kerim'in kalbi kabul edilen sure hangisidir?", options: ["Rahman Suresi", "Mülk Suresi", "Yasin Suresi", "Fetih Suresi"], answerIndex: 2 },
{ question: "Kur'an-ı Kerim'de adı açıkça geçen tek sahabe kimdir?", options: ["Hz. Ebubekir", "Hz. Ömer", "Hz. Ali", "Zeyd bin Harise"], answerIndex: 3 },
{ question: "İlk inen ayetler hangi surenin içindedir?", options: ["Müddessir Suresi", "Alak Suresi", "Kalem Suresi", "Müzemmil Suresi"], answerIndex: 1 },
{ question: "Kur'an-ı Kerim toplam kaç cüzden oluşmaktadır?", options: ["20", "25", "30", "40"], answerIndex: 2 },
{ question: "Hangi peygamberin kıssası Kur'an'da 'Ahsenü'l-Kasas' (Kıssaların en güzeli) olarak adlandırılır?", options: ["Hz. İbrahim", "Hz. Yusuf", "Hz. Musa", "Hz. İsa"], answerIndex: 1 },
{ question: "Kur'an-ı Kerim'de ismi en çok geçen peygamber kimdir?", options: ["Hz. Muhammed", "Hz. İsa", "Hz. İbrahim", "Hz. Musa"], answerIndex: 3 },
{ question: "Ayetü'l-Kürsi hangi surenin içindedir?", options: ["Bakara Suresi", "Al-i İmran Suresi", "Nisa Suresi", "Maide Suresi"], answerIndex: 0 },
{ question: "İki defa besmele geçen sure hangisidir?", options: ["Kehf Suresi", "Neml Suresi", "İsra Suresi", "Taha Suresi"], answerIndex: 1 },
{ question: "İçinde secde ayeti bulunan ilk sure hangisidir?", options: ["Necm Suresi", "Araf Suresi", "Alak Suresi", "Secde Suresi"], answerIndex: 0 },
{ question: "Peygamber Efendimizin (s.a.v) doğduğu gece meydana gelen olaylardan biri olarak bilinen sarayın yıkılması hangi imparatorluğa aittir?", options: ["Bizans", "Roma", "Sasani", "Mısır"], answerIndex: 2 },
{ question: "Peygamber Efendimizin (s.a.v) süt annesinin adı nedir?", options: ["Amine", "Halime", "Ümmü Eymen", "Şeyma"], answerIndex: 1 },
{ question: "Peygamberimize ilk vahyin geldiği Hira Mağarası hangi dağdadır?", options: ["Sevr Dağı", "Uhud Dağı", "Arafat Dağı", "Nur Dağı"], answerIndex: 3 },
{ question: "Habeşistan'a yapılan ilk hicrette Müslüman kafileye başkanlık eden sahabe kimdir?", options: ["Hz. Ömer", "Hz. Osman", "Cafer bin Ebu Talip", "Hz. Hamza"], answerIndex: 2 },
{ question: "Peygamber Efendimizin (s.a.v) Mirac'a yükseldiği mescit hangisidir?", options: ["Mescid-i Haram", "Mescid-i Nebevi", "Mescid-i Aksa", "Kuba Mescidi"], answerIndex: 2 },
{ question: "Medine şehrinin İslamiyet'ten önceki eski adı nedir?", options: ["Yesrib", "Taif", "Hayber", "Yemen"], answerIndex: 0 },
{ question: "Bedir Savaşı hangi yılda yapılmıştır?", options: ["622", "624", "625", "627"], answerIndex: 1 },
{ question: "Uhud Savaşı'nda şehit düşen ve 'Şehitlerin Efendisi' lakabını alan sahabe kimdir?", options: ["Mus'ab bin Umeyr", "Hz. Ali", "Hz. Hamza", "Abdullah bin Revaha"], answerIndex: 2 },
{ question: "Hendek Savaşı'nda şehrin etrafına hendek kazma fikrini veren sahabe kimdir?", options: ["Ammar bin Yasir", "Selman-ı Farisi", "Bilal-i Habeşi", "Zeyd bin Sabit"], answerIndex: 1 },
{ question: "İslam tarihinde büyük bir siyasi zafer kabul edilen antlaşma hangisidir?", options: ["Hudeybiye Antlaşması", "Akabe Biatları", "Veda Hutbesi", "Medine Sözleşmesi"], answerIndex: 0 },
{ question: "Mekke'nin fethi hangi yılda gerçekleşmiştir?", options: ["628", "629", "630", "632"], answerIndex: 2 },
{ question: "Peygamber Efendimizin (s.a.v) kabrinin bulunduğu yere ne ad verilir?", options: ["Cennetü'l-Baki", "Ravza-i Mutahhara", "Kabe-i Muazzama", "Makam-ı İbrahim"], answerIndex: 1 },
{ question: "Peygamber Efendimizin (s.a.v) en küçük kızının adı nedir?", options: ["Zeynep", "Rukiye", "Ümmü Gülsüm", "Fatıma"], answerIndex: 3 },
{ question: "İslam'ın beş şartından biri olan zekat, hicretin kaçıncı yılında farz kılınmıştır?", options: ["1. Yılı", "2. Yılı", "3. Yılı", "5. Yılı"], answerIndex: 1 },
{ question: "Namazda ayakta durmaya ne ad verilir?", options: ["Kıraat", "Rüku", "Secde", "Kıyam"], answerIndex: 3 },
{ question: "Abdestin farzı kaçtır?", options: ["3", "4", "5", "6"], answerIndex: 1 },
{ question: "Gusül (boy abdesti) farzı kaçtır?", options: ["2", "3", "4", "5"], answerIndex: 1 },
{ question: "Su bulunmadığı zaman toprakla alınan abdeste ne denir?", options: ["Taharet", "İstinca", "Teyemmüm", "Gusül"], answerIndex: 2 },
{ question: "Hangi vakit namazının farzı sünnetinden sonra kılınır?", options: ["Öğle", "İkindi", "Akşam", "Sabah"], answerIndex: 3 },
{ question: "Ramazan ayına özgü, yatsı namazından sonra kılınan sünnet namaz hangisidir?", options: ["Teheccüd", "İşrak", "Evvabin", "Teravih"], answerIndex: 3 },
{ question: "Hacca gidenlerin Arafat'ta bir süre beklemelerine ne ad verilir?", options: ["Tavaf", "Sa'y", "Vakfe", "İhram"], answerIndex: 2 },
{ question: "Kabe'nin etrafında bir kez dönmeye ne denir?", options: ["Şavt", "Tavaf", "Hacerü'l-Esved", "Mültezem"], answerIndex: 0 },
{ question: "Kabe'nin etrafında yedi kez dönmeye ne denir?", options: ["Sa'y", "Vakfe", "Şavt", "Tavaf"], answerIndex: 3 },
{ question: "Safa ile Merve tepeleri arasında yedi kez gidip gelmeye ne denir?", options: ["Tavaf", "Sa'y", "Müzdelife", "Mina"], answerIndex: 1 },
{ question: "Aşağıdakilerden hangisine zekat verilebilir?", options: ["Anneye", "Babaya", "Kardeşe", "Çocuğa"], answerIndex: 2 },
{ question: "Nisap miktarı mala sahip olan kişinin yılda bir kez vermesi gereken zekat oranı kaçtır?", options: ["1/10", "1/20", "1/30", "1/40"], answerIndex: 3 },
{ question: "Toprak ürünlerinden alınan zekata ne ad verilir?", options: ["Fıtır", "Öşür", "Haraç", "Cizye"], answerIndex: 1 },
{ question: "Kurban kesmenin fıkhi hükmü nedir?", options: ["Farz", "Vacip", "Sünnet", "Müstehap"], answerIndex: 1 },
{ question: "Oruca başlama vaktine ne ad verilir?", options: ["İftar", "Sahur", "İmsak", "Fecr-i Kazib"], answerIndex: 2 },
{ question: "İlk Müslüman olan kadın sahabe kimdir?", options: ["Hz. Aişe", "Hz. Sümeyye", "Hz. Fatıma", "Hz. Hatice"], answerIndex: 3 },
{ question: "Peygamberimizin 'İlim şehrinin kapısıdır' dediği sahabe kimdir?", options: ["Hz. Ebubekir", "Hz. Ömer", "Hz. Osman", "Hz. Ali"], answerIndex: 3 },
{ question: "Kur'an-ı Kerim'i kitap (mushaf) haline getiren halife kimdir?", options: ["Hz. Ebubekir", "Hz. Ömer", "Hz. Osman", "Hz. Ali"], answerIndex: 0 },
{ question: "Kur'an-ı Kerim'i çoğaltarak önemli merkezlere gönderen halife kimdir?", options: ["Hz. Ebubekir", "Hz. Ömer", "Hz. Osman", "Hz. Ali"], answerIndex: 2 },
{ question: "Adaletiyle tanınan ve Kudüs'ü fetheden halife kimdir?", options: ["Hz. Ebubekir", "Hz. Ömer", "Hz. Osman", "Hz. Ali"], answerIndex: 1 },
{ question: "İslam tarihinde ilk ezanı okuyan müezzin kimdir?", options: ["Zeyd bin Harise", "Ammar bin Yasir", "Bilal-i Habeşi", "Abdullah bin Ümmi Mektum"], answerIndex: 2 },
{ question: "İslam'ın ilk şehidi olan kadın sahabe kimdir?", options: ["Hz. Asiye", "Hz. Sümeyye", "Hz. Hatice", "Hz. Fatıma"], answerIndex: 1 },
{ question: "'Allah'ın kılıcı' (Seyfullah) lakabıyla bilinen ünlü İslam komutanı kimdir?", options: ["Halid bin Velid", "Sad bin Ebi Vakkas", "Tarık bin Ziyad", "Ebu Ubeyde bin Cerrah"], answerIndex: 0 },
{ question: "Peygamberimizi hicret yolculuğunda evinde misafir eden Ebu Eyyüb el-Ensari'nin kabri hangi ilimizdedir?", options: ["Bursa", "Konya", "İstanbul", "Şanlıurfa"], answerIndex: 2 },
{ question: "'Aşere-i Mübeşşere' ne demektir?", options: ["Cennetle müjdelenen 10 sahabe", "Kur'an'ı ezberleyen sahabeler", "Bedir savaşına katılanlar", "Peygamberimizin hadislerini yazanlar"], answerIndex: 0 },
{ question: "Uhud Savaşı'nda okçuların komutanı olan sahabe kimdir?", options: ["Mus'ab bin Umeyr", "Abdullah bin Cübeyr", "Zübeyr bin Avvam", "Talha bin Ubeydullah"], answerIndex: 1 },
{ question: "Kur'an-ı Kerim'in 'Gelin'i (Arusu) olarak bilinen sure hangisidir?", options: ["Yasin Suresi", "Rahman Suresi", "Vakıa Suresi", "Mülk Suresi"], answerIndex: 1 },
{ question: "Ebrehe ve ordusunun Kabe'yi yıkmaya gelmesini anlatan sure hangisidir?", options: ["Fil Suresi", "Kureyş Suresi", "Maun Suresi", "Kevser Suresi"], answerIndex: 0 },
{ question: "Kur'an-ı Kerim'de aşağıdaki hayvanlardan hangisinin adını taşıyan bir sure yoktur?", options: ["İnek (Bakara)", "Arı (Nahl)", "Karınca (Neml)", "Aslan (Esed)"], answerIndex: 3 },
{ question: "Peygamber Efendimiz (S.A.V) doğduğunda ona 'Muhammed' ismini kim vermiştir?", options: ["Annesi Amine", "Amcası Ebu Talip", "Dedesi Abdülmuttalip", "Sütannesi Halime"], answerIndex: 2 },
{ question: "Peygamberimizin hicret sırasında bindiği devenin adı nedir?", options: ["Burak", "Düldül", "Kasva", "Kıtmîr"], answerIndex: 2 },
{ question: "Peygamberimizin peygamberlikten önceki lakabı nedir?", options: ["Muhammedü'l-Emin", "Seyyidü'l-Mürselin", "Hatemü'l-Enbiya", "Habibullah"], answerIndex: 0 },
{ question: "Peygamber Efendimiz (S.A.V) annesi vefat ettiğinde kaç yaşındaydı?", options: ["4", "6", "8", "10"], answerIndex: 1 },
{ question: "Peygamberimizin dedesi Abdülmuttalip vefat ettiğinde Peygamberimiz kaç yaşındaydı?", options: ["6", "8", "10", "12"], answerIndex: 1 },
{ question: "Hüzün Yılı (Amü'l-Hüzn) olarak bilinen yılda Peygamberimiz kimleri kaybetmiştir?", options: ["Hz. Hamza ve Hz. Ömer", "Hz. Ali ve Hz. Fatıma", "Dedesi ve Annesi", "Ebu Talip ve Hz. Hatice"], answerIndex: 3 },
{ question: "Peygamberimizin erkek çocuklarından hangisi Medine'de doğmuştur?", options: ["Kasım", "Abdullah", "İbrahim", "Tayyip"], answerIndex: 2 },
{ question: "Cenaze namazının diğer namazlardan en belirgin farkı nedir?", options: ["Rüku ve secdenin olmaması", "Abdest gerektirmemesi", "Sadece camide kılınması", "Kıbleye dönülmemesi"], answerIndex: 0 },
{ question: "Abdest alırken yıkanması farz olan organlardan biri hangisidir?", options: ["Ense", "Yüz", "Kulak", "Ağız"], answerIndex: 1 },
{ question: "Yatsı namazından sonra kılınan Vitir namazı kaç rekattır?", options: ["2", "3", "4", "5"], answerIndex: 1 },
{ question: "Kasten ve mazeretsiz olarak bozulan oruç için tutulması gereken cezai oruca ne denir?", options: ["Kaza", "Keffaret", "Adak", "Nafile"], answerIndex: 1 },
{ question: "Ramazan ayının son 10 gününde dünya işlerinden uzaklaşarak camide ibadete çekilmeye ne denir?", options: ["İhram", "Vakfe", "Tavaf", "İtikaf"], answerIndex: 3 },
{ question: "Yolculuk (seferi) halinde dört rekatlık farz namazlar kaç rekat olarak kılınır?", options: ["2", "3", "4", "Kılınmaz"], answerIndex: 0 },
{ question: "'Zinnureyn' (İki Nur Sahibi) lakabıyla bilinen, Peygamberimizin iki kızıyla evlenmiş olan halife kimdir?", options: ["Hz. Ebubekir", "Hz. Ömer", "Hz. Osman", "Hz. Ali"], answerIndex: 2 },
{ question: "İslam'ın ilk öğretmeni (muallimi) olarak Medine'ye gönderilen sahabe kimdir?", options: ["Bilal-i Habeşi", "Mus'ab bin Umeyr", "Zeyd bin Sabit", "Ammar bin Yasir"], answerIndex: 1 },
{ question: "Peygamberimizden en çok hadis rivayet eden sahabe kimdir?", options: ["Hz. Aişe", "Hz. Ali", "Hz. Ömer", "Ebu Hureyre"], answerIndex: 3 },
{ question: "'Hak ile batılı birbirinden ayıran' anlamına gelen 'Faruk' lakabı hangi halifeye aittir?", options: ["Hz. Ebubekir", "Hz. Ömer", "Hz. Osman", "Hz. Ali"], answerIndex: 1 },
{ question: "Allah yolunda ilk ok atan ve Kadisiye Savaşı'nın muzaffer komutanı olan sahabe kimdir?", options: ["Sad bin Ebi Vakkas", "Halid bin Velid", "Zübeyr bin Avvam", "Ebu Ubeyde bin Cerrah"], answerIndex: 0 },
{ question: "Mısır'ı fetheden ve oranın ilk valisi olan ünlü sahabe kimdir?", options: ["Hz. Hamza", "Muaviye bin Ebu Süfyan", "Amr bin As", "Tarık bin Ziyad"], answerIndex: 2 },
{ question: "Peygamberimizin sırdaşı olarak bilinen ve münafıkların listesi kendisine verilen sahabi kimdir?", options: ["Hz. Ebubekir", "Huzeyfe bin Yeman", "Zeyd bin Harise", "Selman-ı Farisi"], answerIndex: 1 },
{ question: "Kur'an-ı Kerim'de yer alan 'İhlas' kelimesinin anlamı nedir?", options: ["Samimiyet, içtenlik", "Güç ve Kudret", "Merhamet", "Adalet"], answerIndex: 0 },
{ question: "Aşağıdakilerden hangisi namazın dışındaki farzlarından (şartlarından) biridir?", options: ["Kıyam", "Rüku", "Secde", "İstikbal-i Kıble (Kıbleye yönelmek)"], answerIndex: 3 },
{ question: "Aşağıdakilerden hangisi namazın içindeki farzlarından (rükünlerinden) biridir?", options: ["Necasetten Taharet", "Vakit", "Secde", "Niyet"], answerIndex: 2 },
{ question: "Zekat verecek kişinin dinen zengin sayılabilmesi için sahip olması gereken asgari zenginlik ölçüsüne ne denir?", options: ["Fıtır", "Nisap", "Öşür", "Mihir"], answerIndex: 1 },
{ question: "Ramazan bayramından önce verilmesi vacip olan sadaka hangisidir?", options: ["Fıtır Sadakası (Fitre)", "Zekat", "Fidye", "Keffaret"], answerIndex: 0 },
{ question: "Kur'an-ı Kerim'de adı geçen ve kendisine 'Zebur' adlı ilahi kitap verilen peygamber kimdir?", options: ["Hz. Musa", "Hz. Davud", "Hz. İsa", "Hz. Süleyman"], answerIndex: 1 },
{ question: "Hangi peygamberin lakabı 'Kelimullah' (Allah ile doğrudan konuşan) dır?", options: ["Hz. İbrahim", "Hz. İsa", "Hz. Musa", "Hz. Nuh"], answerIndex: 2 },
{ question: "Hangi peygamberin lakabı 'Halilullah' (Allah'ın dostu) dır?", options: ["Hz. İbrahim", "Hz. Muhammed", "Hz. Yakup", "Hz. Yusuf"], answerIndex: 0 },
{ question: "Kur'an-ı Kerim'de insanlar için şifa olduğu belirtilen yiyecek hangisidir?", options: ["Zeytin", "Bal", "Hurma", "İncir"], answerIndex: 1 },
{ question: "Su bulunmadığında teyemmüm abdesti alırken hangi madde kullanılır?", options: ["Su", "Yaprak", "Kumaş", "Temiz Toprak"], answerIndex: 3 },
{ question: "İslam fıkhında 'Haram' kelimesi ne anlama gelir?", options: ["Kesin ve bağlayıcı bir şekilde yasaklanan eylem", "Yapılması tavsiye edilen eylem", "Yapılmasında sakınca olmayan eylem", "Hoş karşılanmayan ancak yasak olmayan eylem"], answerIndex: 0 },
{ question: "Cuma namazının farzı kaç rekattır?", options: ["1", "2", "3", "4"], answerIndex: 1 },
{ question: "Aşağıdaki hayvanlardan hangisinin kurban edilmesi caizdir?", options: ["Tavuk", "Geyik", "Keçi", "At"], answerIndex: 2 },
{ question: "Kur'an-ı Kerim'in en son suresi hangisidir?", options: ["İhlas Suresi", "Felak Suresi", "Fatiha Suresi", "Nas Suresi"], answerIndex: 3 },
{ question: "'Mevlid' kelimesinin sözlük anlamı nedir?", options: ["Doğum zamanı ve yeri", "Yükseliş", "Gece yürüyüşü", "Göç etmek"], answerIndex: 0 },
{ question: "Peygamber Efendimiz Taif'te taşlandığında, dağların meleği gelip 'Onları helak edeyim mi?' diye sorduğunda Peygamberimiz nasıl cevap vermiştir?", options: ["Evet, cezalarını bulsunlar.", "Hayır, onların soyundan Allah'a ibadet edenler çıkacak.", "Sadece liderlerini helak et.", "Onları şehirden sürgün et."], answerIndex: 1 },
{ question: "Mekkeli müşriklerin Müslümanlara uyguladığı ve tam 3 yıl süren olay nedir?", options: ["Sürgün", "Hicret", "Boykot (Ambargo)", "Savaş"], answerIndex: 2 },
{ question: "Mekke'den Medine'ye göç eden Müslümanlara yardım eden Medineli Müslümanlara ne isim verilir?", options: ["Muhacir", "Ensar", "Sahabe", "Tabiin"], answerIndex: 1 },
{ question: "Dinleri uğruna Mekke'den Medine'ye göç eden Müslümanlara ne isim verilir?", options: ["Muhacir", "Ensar", "Mücahid", "Mümin"], answerIndex: 0 },
{ question: "Kur'an-ı Kerim'de 'Tebbet' suresinde kendisinden ve eşinden bahsedilen, Peygamberimizin İslam düşmanı amcası kimdir?", options: ["Ebu Talip", "Abbas", "Hamza", "Ebu Leheb"], answerIndex: 3 },
{ question: "Hz. Ali'nin babası ve Peygamberimizin amcası olan, Peygamberimizi hayatı boyunca koruyan kişi kimdir?", options: ["Ebu Leheb", "Haris", "Ebu Talip", "Muttalip"], answerIndex: 2 },
{ question: "Miraç gecesinde Peygamberimize ve ümmetine farz kılınan ibadet hangisidir?", options: ["Oruç", "Namaz", "Zekat", "Hac"], answerIndex: 1 },
{ question: "İslam literatüründe 'Kütüb-i Sitte' ne anlama gelmektedir?", options: ["Altı güvenilir hadis kitabı", "Kur'an'ın altı bölümü", "İmanın altı şartı", "İslam'ın altı büyük savaşı"], answerIndex: 0 },
{ question: "Ezan okunurken müezzinin okuduğu sözleri tekrarladıktan sonra okunan duaya ne denir?", options: ["Sübhaneke", "Tahiyyat", "Ezan Duası", "Kunut Duası"], answerIndex: 2 },
{ question: "İslam dininde imanın şartları hangi kelime-i kavram ile özetlenir?", options: ["Kelime-i Şehadet", "Amentü", "Kelime-i Tevhid", "Besmele"], answerIndex: 1 },
{ question: "İslam tarihinde Müslümanların ilk başkenti neresidir?", options: ["Mekke", "Kudüs", "Şam", "Medine"], answerIndex: 3 },
{ question: "Yüce Allah'ın varlığı ve birliğine inanmak, eşi ve benzeri olmadığını kabul etmeye ne ad verilir?", options: ["Tevhid", "Şirk", "Nifak", "Kıyam"], answerIndex: 0 },
{ question: "Kur'an-ı Kerim'de 'Şehirlerin Anası' (Ümmü'l-Kurâ) olarak anılan şehir neresidir?", options: ["Kudüs", "Medine", "Mekke", "Taif"], answerIndex: 2 },
{ question: "Kur'an'da adı geçen, peygamber olup olmadığı ihtilaflı olan ve oğluna verdiği öğütlerle bilinen zat kimdir?", options: ["Hz. Hızır", "Lokman Hekim", "Zülkarneyn", "Talut"], answerIndex: 1 },
{ question: "'Zülkarneyn' kıssası Kur'an-ı Kerim'de hangi surede anlatılmaktadır?", options: ["Kehf Suresi", "Yasin Suresi", "Enbiya Suresi", "Kasas Suresi"], answerIndex: 0 },
{ question: "Hangi peygamberin mucizesi olarak elindeki asası yılana dönüşmüştür?", options: ["Hz. İsa", "Hz. İbrahim", "Hz. Musa", "Hz. Süleyman"], answerIndex: 2 },
{ question: "Kur'an-ı Kerim'de bazı surelerin başında bulunan ve 'Kesik harfler' anlamına gelen harflere ne denir?", options: ["Harf-i Cer", "Huruf-u Mukattaa", "Tecvid", "Tefsir"], answerIndex: 1 },
{ question: "Kur'an-ı Kerim'de 'İmran Ailesi' anlamına gelen sure hangisidir?", options: ["Al-i İmran Suresi", "Meryem Suresi", "Maide Suresi", "En'am Suresi"], answerIndex: 0 },
{ question: "Kur'an-ı Kerim'de 'Gökten indirilen sofra' manasına gelen sure hangisidir?", options: ["Nisa Suresi", "Araf Suresi", "Maide Suresi", "Enfal Suresi"], answerIndex: 2 },
{ question: "Yüce Allah'ın isimlerinden (Esma-ül Hüsna) 'Er-Rezzak' ne anlama gelir?", options: ["Çok merhamet eden", "Bütün mahlukatın rızkını veren", "Her şeyi hakkıyla işiten", "Günahları bağışlayan"], answerIndex: 1 },
{ question: "Kur'an-ı Kerim'de Firavun'un eşi olarak övülen imanlı kadın kimdir?", options: ["Hz. Meryem", "Hz. Asiye", "Hz. Hacer", "Hz. Sare"], answerIndex: 1 },
{ question: "Kur'an'da 'İki denizin birbirine kavuştuğu ama sularının karışmadığı' mucizesinden bahseden sure hangisidir?", options: ["Rahman Suresi", "Vakıa Suresi", "Yunus Suresi", "Furkan Suresi"], answerIndex: 0 },
{ question: "Peygamber Efendimiz (s.a.v) ve Hz. Ebubekir'in Medine'ye hicret ederken gizlendikleri mağara hangisidir?", options: ["Hira Mağarası", "Sevr Mağarası", "Ashab-ı Kehf", "Arafat"], answerIndex: 1 },
{ question: "İlk vahiy geldiğinde Hz. Hatice'nin, Peygamberimizi götürüp durumu danıştığı bilgin akrabası kimdir?", options: ["Ebu Talip", "Varaka bin Nevfel", "Abdülmuttalip", "Zeyd bin Amr"], answerIndex: 1 },
{ question: "Peygamber Efendimizin (s.a.v) dedesi Abdülmuttalip'in asıl adı nedir?", options: ["Şeybe", "Amr", "Haşim", "Kusay"], answerIndex: 0 },
{ question: "İslamiyet'ten önce Arabistan'da haram aylarda yapılan savaşlara ne ad verilirdi?", options: ["Ficar Savaşları", "Gaza", "Seriyye", "Cihad"], answerIndex: 0 },
{ question: "Peygamberimizin gençliğinde katıldığı, haksızlığa uğrayanları korumak için kurulan cemiyetin adı nedir?", options: ["Darü'n-Nedve", "Darü'l-Erkam", "Hılfu'l-Fudûl", "Suffe"], answerIndex: 2 },
{ question: "Peygamber Efendimizin Medine'de devesi Kasva'nın çöktüğü arsaya inşa edilen mescit hangisidir?", options: ["Kuba Mescidi", "Mescid-i Kıbleteyn", "Mescid-i Nebevi", "Mescid-i Aksa"], answerIndex: 2 },
{ question: "Hz. Hamza'yı Uhud Savaşı'nda şehit eden mızrakçı köle kimdir?", options: ["Ebu Cehil", "Ebu Süfyan", "Ümeyye bin Halef", "Vahşi"], answerIndex: 3 },
{ question: "Müslümanların Mekke'den Medine'ye göç etmesinin ardından Müşriklerle yapılan ilk büyük savaş hangisidir?", options: ["Bedir Savaşı", "Uhud Savaşı", "Hendek Savaşı", "Mute Savaşı"], answerIndex: 0 },
{ question: "Peygamber Efendimiz Taif'ten dönerken sığındığı bağda ona üzüm ikram eden Hristiyan köle kimdir?", options: ["Zeyd", "Addas", "Selman", "Bilal"], answerIndex: 1 },
{ question: "Müslümanların 'Okçular Tepesi'nin terk edilmesiyle zor anlar yaşadığı savaş hangisidir?", options: ["Bedir Savaşı", "Hendek Savaşı", "Uhud Savaşı", "Hayber'in Fethi"], answerIndex: 2 },
{ question: "Cenaze yıkanırken ve kefenlenirken yapılan işlemlere fıkıhta genel olarak ne ad verilir?", options: ["Gusül", "Teyemmüm", "Teçhiz ve Tekfin", "Defin"], answerIndex: 2 },
{ question: "Namazda rükûdan kalkarken 'Semiallahu limen hamideh' demenin fıkhi hükmü nedir?", options: ["Farz", "Sünnet", "Vacip", "Mekruh"], answerIndex: 1 },
{ question: "Ramazan orucunu bilerek ve mazeretsiz bozmanın cezası olan 'Keffaret' orucu aralıksız kaç gün tutulmalıdır?", options: ["30 gün", "40 gün", "60 gün", "90 gün"], answerIndex: 2 },
{ question: "Camilerde cuma ve bayram namazlarında imamın hutbe okumak için çıktığı basamaklı yere ne denir?", options: ["Mihrap", "Kürsü", "Minber", "Mahfil"], answerIndex: 2 },
{ question: "Camiilerde imamın cemaate namaz kıldırırken durduğu, kıble yönündeki oyuk yere ne ad verilir?", options: ["Minber", "Mihrap", "Şadırvan", "Eyvan"], answerIndex: 1 },
{ question: "Dişlerin temizlenmesi için kullanılan, Peygamberimizin de çokça tavsiye ettiği ağaç dalına ne ad verilir?", options: ["Reyhan", "Misvak", "Öd Ağacı", "Kına"], answerIndex: 1 },
{ question: "Farz namazlardan önce müezzinin okuduğu ve cemaati namaza kalkmaya çağıran sözlere ne denir?", options: ["Kamet", "Sela", "Tekbir", "Tesbihat"], answerIndex: 0 },
{ question: "Kurban bayramı günlerinde farz namazlardan sonra okunan tekbirlere ne ad verilir?", options: ["Teşrik Tekbirleri", "İftitah Tekbiri", "Zevaid Tekbirleri", "İntikal Tekbirleri"], answerIndex: 0 },
{ question: "İslâm dinine göre kullanılması, yenilip içilmesi yasaklanmamış olan şeylere ne denir?", options: ["Mekruh", "Mubah", "Helal", "Farz"], answerIndex: 2 },
{ question: "Zengin sayılan Müslümanların, malının kırkta birini (%2.5) ibadet niyetiyle yoksullara vermesine ne denir?", options: ["Fitre", "Zekat", "Sadaka", "Öşür"], answerIndex: 1 },
{ question: "Peygamber Efendimize vahiy katipliği yapan ve Kur'an'ın kitap haline getirilmesinde komisyon başkanı olan sahabe kimdir?", options: ["Hz. Ömer", "Hz. Ali", "Zeyd bin Sabit", "Abdullah bin Mesud"], answerIndex: 2 },
{ question: "'Seyfullah' (Allah'ın Kılıcı) lakaplı, Mute savaşının efsanevi komutanı kimdir?", options: ["Halid bin Velid", "Sad bin Ebi Vakkas", "Ebu Ubeyde bin Cerrah", "Hz. Hamza"], answerIndex: 0 },
{ question: "Mekke'nin fethinde Kabe'nin üzerine çıkarak ezan okuyan sahabe kimdir?", options: ["Ammar bin Yasir", "Bilal-i Habeşi", "Zeyd bin Harise", "Usame bin Zeyd"], answerIndex: 1 },
{ question: "Hayber Kalesi'nin fethinde gösterdiği kahramanlıklarla 'Haydar-ı Kerrar' lakabını alan sahabe kimdir?", options: ["Hz. Hamza", "Hz. Ali", "Hz. Ömer", "Hz. Ebubekir"], answerIndex: 1 },
{ question: "Hz. Ebubekir'in kızı olan ve hicret sırasında 'Zatü'n-Nitakayn' (İki Kuşaklı) lakabını alan kadın sahabe kimdir?", options: ["Hz. Aişe", "Esma bint Ebubekir", "Hz. Hafsa", "Hz. Fatıma"], answerIndex: 1 },
{ question: "Kudüs'ün fethedilmesinden sonra şehrin anahtarlarını bizzat teslim almaya giden halife kimdir?", options: ["Hz. Ebubekir", "Hz. Ömer", "Hz. Osman", "Hz. Ali"], answerIndex: 1 },
{ question: "Peygamber Efendimiz vefat ettiğinde inanmak istemeyip 'Kim Muhammed öldü derse kılıcımla boynunu vururum' diyen halife kimdir?", options: ["Hz. Osman", "Hz. Ali", "Hz. Ömer", "Hz. Ebubekir"], answerIndex: 2 },
{ question: "Peygamberimize tıpatıp benzeyen ve Uhud'da şehit düştüğünde meleklerin ağladığı söylenen, Medine'nin ilk öğretmeni kimdir?", options: ["Mus'ab bin Umeyr", "Zeyd bin Harise", "Cafer bin Ebu Talip", "Ammar bin Yasir"], answerIndex: 0 },
{ question: "Hz. Osman'ı şehit eden isyancılara karşı adaleti sağlamak amacıyla yapılan ve Hz. Aişe'nin devesi etrafında gerçekleşen savaşa ne ad verilir?", options: ["Sıffin Savaşı", "Cemel Vakası", "Nehrevan Savaşı", "Yermük Savaşı"], answerIndex: 1 },
{ question: "'Ümmetin Emini' lakabıyla anılan ve Hz. Ömer'in 'Yaşasaydı halifeliği ona bırakırdım' dediği sahabe kimdir?", options: ["Abdurrahman bin Avf", "Talha bin Ubeydullah", "Zübeyr bin Avvam", "Ebu Ubeyde bin Cerrah"], answerIndex: 3 },
{ question: "İslamiyet'ten önce Mekkeli müşriklerin Kabe'de tapındıkları en büyük putun adı nedir?", options: ["Lat", "Menat", "Uzza", "Hubel"], answerIndex: 3 },
{ question: "'Ben cinleri ve insanları, ancak bana kulluk etsinler diye yarattım.' ayeti hangi surededir?", options: ["Zariyat Suresi", "Bakara Suresi", "Yasin Suresi", "Mülk Suresi"], answerIndex: 0 },
{ question: "Kıyamet günü insanların diriltilip hesap vermek üzere Allah'ın huzurunda toplanacakları büyük alana ne ad verilir?", options: ["Mizan", "Sırat", "Mahşer", "Araf"], answerIndex: 2 },
{ question: "İnsanın öldükten sonra kabre konulmasıyla başlayan ve kıyamete kadar sürecek olan ara döneme ne ad verilir?", options: ["Ahiret", "Berzah", "Haşr", "Ba's"], answerIndex: 1 },
{ question: "Kendisine 'Kelimetullah' (Allah'ın kelimesi) ve 'Ruhullah' lakapları verilen peygamber kimdir?", options: ["Hz. İbrahim", "Hz. Musa", "Hz. İsa", "Hz. Yahya"], answerIndex: 2 },
{ question: "Şeytanın Allah'ın huzurundan kovulmasına sebep olan kibri yüzünden secde etmeyi reddettiği peygamber kimdir?", options: ["Hz. Adem", "Hz. İdris", "Hz. Nuh", "Hz. İbrahim"], answerIndex: 0 },
{ question: "Nemrut tarafından ateşe atıldığında, ateşin kendisine 'serin ve selamet' olduğu peygamber kimdir?", options: ["Hz. Yakup", "Hz. İsmail", "Hz. Lut", "Hz. İbrahim"], answerIndex: 3 },
{ question: "Güzelliğiyle meşhur olan ve kardeşleri tarafından kıskanılıp kuyuya atılan peygamber kimdir?", options: ["Hz. Yunus", "Hz. Yusuf", "Hz. Eyyub", "Hz. Şuayb"], answerIndex: 1 },
{ question: "Sabrıyla örnek gösterilen, uzun süre ağır bir hastalık geçirip hiç isyan etmeyen peygamber kimdir?", options: ["Hz. Eyyub", "Hz. Davud", "Hz. Süleyman", "Hz. Elyesa"], answerIndex: 0 },
{ question: "Yaptığı gemiyle inananları ve her canlıdan birer çifti büyük tufandan kurtaran peygamber kimdir?", options: ["Hz. Hud", "Hz. Salih", "Hz. Nuh", "Hz. Lut"], answerIndex: 2 },
{ question: "Kur'an-ı Kerim'in diğer isimlerinden biri olan ve 'Hak ile batılı ayıran' anlamına gelen isim hangisidir?", options: ["Zikir", "Şifa", "Furkan", "Beyan"], answerIndex: 2 },
{ question: "Kabe'nin üzerine örtülen siyah örtüye ne ad verilir?", options: ["Hacerü'l-Esved", "Kisve", "Makam", "Mültezem"], answerIndex: 1 },
{ question: "İslam tarihinde inşa edilen ilk mescit hangisidir?", options: ["Kuba Mescidi", "Mescid-i Nebevi", "Mescid-i Aksa", "Mescid-i Haram"], answerIndex: 0 },
{ question: "Peygamberimizin Medine'ye hicretinde devesi Kasva'nın çöktüğü arsanın sahipleri olan yetim kardeşler kimlerdir?", options: ["Hasan ve Hüseyin", "Sehl ve Süheyl", "Enes ve Malik", "Sad ve Said"], answerIndex: 1 },
{ question: "Peygamber Efendimizin (s.a.v) bizzat komuta ederek katıldığı savaşlara ne ad verilir?", options: ["Seriyye", "Gaza (Gazve)", "Cihat", "Kıtal"], answerIndex: 1 },
{ question: "Peygamber Efendimizin (s.a.v) bizzat katılmayıp komutan atadığı askeri birliklere ne ad verilir?", options: ["Gazve", "Ordu", "Seriyye", "Bölük"], answerIndex: 2 },
{ question: "Kur'an-ı Kerim'de toplam kaç tane secde ayeti bulunmaktadır?", options: ["10", "12", "14", "16"], answerIndex: 2 },
{ question: "Müslümanlar ile Yahudiler arasında yapılan ve Medine'nin birlikte savunulmasını içeren antlaşmanın adı nedir?", options: ["Hudeybiye Antlaşması", "Akabe Biatı", "Medine Sözleşmesi", "Veda Hutbesi"], answerIndex: 2 },
{ question: "Mekke'nin fethinden sonra Kabe'nin anahtarlarını koruma ve kapısını açma görevi (Hicabe) Peygamberimiz tarafından kime verilmiştir?", options: ["Osman bin Talha", "Ebu Süfyan", "Abbas bin Abdülmuttalip", "Hz. Ali"], answerIndex: 0 },
{ question: "Cuma ve Bayram namazlarında imamın minbere çıkarak cemaate yaptığı konuşmaya ne ad verilir?", options: ["Sohbet", "Vaaz", "Hutbe", "Kıraat"], answerIndex: 2 },
{ question: "Vefat eden bir Müslümanı İslami usullere göre yıkayan kişiye ne ad verilir?", options: ["İmam", "Müezzin", "Gassal", "Kefenleyici"], answerIndex: 2 },
{ question: "Namazda rüku ve secdelerde okunan dualara genel olarak ne ad verilir?", options: ["Tekbir", "Tahmid", "Tahlil", "Tesbihat"], answerIndex: 3 },
{ question: "Farz veya vacip olan bir ibadetin vaktinden sonra yerine getirilmesine ne ad verilir?", options: ["Eda", "Kaza", "Nafile", "Sünnet"], answerIndex: 1 },
{ question: "Bir ibadetin kendi vakti içinde yerine getirilmesine ne ad verilir?", options: ["Kaza", "Eda", "İade", "Cem"], answerIndex: 1 },
{ question: "Hz. Ebubekir'in halifeliği döneminde ortaya çıkan yalancı peygamberlerin en meşhuru kimdir?", options: ["Müseylemetü'l-Kezzab", "Esved el-Ansi", "Tuleyha bin Huveylid", "Secah"], answerIndex: 0 },
{ question: "Bizans ordusuna karşı kazanılan ve Suriye'nin kapılarını Müslümanlara açan Yermük Savaşı'nın başkomutanı kimdi?", options: ["Ebu Ubeyde bin Cerrah", "Sad bin Ebi Vakkas", "Halid bin Velid", "Amr bin As"], answerIndex: 2 },
{ question: "Rüyasında ezanı görerek Peygamberimize anlatan ve ezan sözlerinin belirlenmesine vesile olan sahabe kimdir?", options: ["Bilal-i Habeşi", "Abdullah bin Zeyd", "Hz. Ömer", "Ammar bin Yasir"], answerIndex: 1 },
{ question: "Kur'an-ı Kerim'de 'Şüphesiz biz sana apaçık bir fetih verdik' (Fetih Suresi) ayetiyle müjdelenen antlaşma hangisidir?", options: ["Akabe Biatı", "Medine Sözleşmesi", "Hudeybiye Antlaşması", "Taif Antlaşması"], answerIndex: 2 },
{ question: "Kur'an-ı Kerim'in tamamını ezberleyen kişiye ne ad verilir?", options: ["Kari", "Hafız", "Müfessir", "Muhaddis"], answerIndex: 1 },
{ question: "Hz. Muhammed'in (s.a.v) doğumunu, hayatını ve mucizelerini anlatan, Süleyman Çelebi'nin meşhur eserinin türü nedir?", options: ["Mevlid", "Siyer", "Hadis", "Tefsir"], answerIndex: 0 },
{ question: "Hz. Hasan ve Hz. Hüseyin'in soyundan gelenlere, yani Peygamberimizin soyunu devam ettirenlere ne ad verilir?", options: ["Ensar", "Muhacir", "Seyyid ve Şerif", "Sahabe"], answerIndex: 2 },
{ question: "Ramazan ayında hafızların veya Kur'an'ı iyi okuyanların cemaate Kur'an okuması ve cemaatin de takip etmesine ne denir?", options: ["Hatim", "Mukabele", "Tefsir", "Tilavet"], answerIndex: 1 },
{ question: "Zengin sayılan Müslümanların koyun ve keçi gibi küçükbaş hayvanlar için zekat vermesi gereken nisap miktarı (en az sayı) kaçtır?", options: ["30", "40", "50", "60"], answerIndex: 1 },
{ question: "Sığır ve manda gibi büyükbaş hayvanlar için zekat nisap miktarı kaçtır?", options: ["20", "30", "40", "50"], answerIndex: 1 },
{ question: "Altın için belirlenen zekat nisap miktarı kaç gramdır?", options: ["50 gram", "60.5 gram", "80.18 gram", "100 gram"], answerIndex: 2 },
{ question: "Hac ibadeti için ihrama girilmesi zorunlu olan sınır noktalarına ne ad verilir?", options: ["Mikat", "Arafat", "Müzdelife", "Mina"], answerIndex: 0 },
{ question: "Hacda Safa ve Merve tepeleri arasında yapılan yürüyüş sırasında erkeklerin kısa adımlarla hafif koşar gibi yürümesine ne denir?", options: ["Tavaf", "Hervele", "Vakfe", "Şavt"], answerIndex: 1 },
{ question: "Arafat'ta vakfe yapıldıktan sonra güneş batınca geçilen ve taş toplamak için beklenen yer neresidir?", options: ["Safa", "Merve", "Müzdelife", "Mina"], answerIndex: 2 },
{ question: "Hac ibadeti sırasında şeytan taşlama işleminin yapıldığı ve kurbanların kesildiği yer neresidir?", options: ["Arafat", "Müzdelife", "Mina", "Kabe"], answerIndex: 2 },
{ question: "Peygamber Efendimizin bildirdiğine göre cennetteki en yüksek makamın adı nedir?", options: ["Firdevs", "Adn", "Naim", "Me'va"], answerIndex: 0 },
{ question: "Cehennemin bekçisi olan ve Kur'an'da da adı geçen meleğin adı nedir?", options: ["Rıdvan", "Malik", "Zebani", "Azrail"], answerIndex: 1 },
{ question: "Cennetin bekçisi olmakla görevli meleğin adı nedir?", options: ["Rıdvan", "Malik", "Mikail", "İsrafil"], answerIndex: 0 },
{ question: "Peygamber Efendimize (s.a.v) 'Ebu'l-Kasım' künyesinin verilmesinin sebebi nedir?", options: ["İlk çocuğu olan Kasım'dan dolayı", "Amcasının adı olduğu için", "Kabe'yi inşa edenlerden olduğu için", "Araplarda saygı ifadesi olduğu için"], answerIndex: 0 },
{ question: "Peygamberimizin eşlerine, inananların anneleri anlamında verilen unvan nedir?", options: ["Ehl-i Beyt", "Ümmehatü'l-Müminin", "Muhacir", "Hulefa-yi Raşidin"], answerIndex: 1 },
{ question: "İslam ordularının Mısır'ı fethetmesini sağlayan komutan ve ilk Mısır valisi kimdir?", options: ["Halid bin Velid", "Sad bin Ebi Vakkas", "Amr bin As", "Ebu Ubeyde bin Cerrah"], answerIndex: 2 },
{ question: "Kıbrıs Adası hangi halife döneminde inşa edilen donanma ile fethedilmiştir?", options: ["Hz. Ebubekir", "Hz. Ömer", "Hz. Osman", "Hz. Ali"], answerIndex: 2 },
{ question: "Hz. Ali ile Muaviye arasında gerçekleşen ve hakem olayı ile sonuçlanan savaşın adı nedir?", options: ["Sıffin Savaşı", "Cemel Vakası", "Nehrevan Savaşı", "Kadisiye Savaşı"], answerIndex: 0 },
{ question: "Peygamberimizin torunu Hz. Hüseyin ve beraberindekilerin şehit edildiği Kerbela Olayı hangi yılda gerçekleşmiştir?", options: ["632", "656", "661", "680"], answerIndex: 3 },
{ question: "Hz. Aişe'ye münafıklar tarafından atılan ve Allah'ın ayet indirerek (Nur Suresi) onun masumiyetini bildirdiği iftira olayına ne denir?", options: ["Fil Vakası", "Ficar Olayı", "İfk Hadisesi", "Rıdvan Biatı"], answerIndex: 2 },
{ question: "Mazeretsiz olarak Tebük Seferi'ne katılmayan ancak samimi pişmanlıkları üzerine tevbeleri Allah tarafından kabul edilen üç sahabeden en çok bilineni kimdir?", options: ["Ka'b bin Malik", "Ammar bin Yasir", "Bilal-i Habeşi", "Zeyd bin Harise"], answerIndex: 0 },
{ question: "Mekke'nin fethi sırasında Kabe'nin içindeki ve etrafındaki 360 putu Peygamberimizle birlikte temizleyen sahabe kimdir?", options: ["Hz. Ebubekir", "Hz. Ömer", "Hz. Ali", "Hz. Osman"], answerIndex: 2 },
{ question: "Mute Savaşı'nda sırasıyla komutayı devralan ve üçü de şehit düşen sahabeler kimlerdir?", options: ["Hz. Ali - Hz. Hamza - Halid bin Velid", "Zeyd bin Harise - Cafer bin Ebu Talip - Abdullah bin Revaha", "Ebu Ubeyde - Amr bin As - Mus'ab bin Umeyr", "Talha - Zübeyr - Sad bin Ebi Vakkas"], answerIndex: 1 },
{ question: "Peygamberimizin vefatından sonra ilk halifenin (Hz. Ebubekir) seçimi nerede yapılmıştır?", options: ["Mescid-i Nebevi'de", "Beni Saide Gölgeliğinde (Sakifetü Beni Saide)", "Hz. Aişe'nin evinde", "Kuba Mescidi'nde"], answerIndex: 1 },
{ question: "Dinimizde kesin bir delille yasaklanmamış olmakla birlikte, yapılması hoş karşılanmayan işlere ne ad verilir?", options: ["Mekruh", "Haram", "Mubah", "Müstehap"], answerIndex: 0 },
{ question: "Kıyamet gününde insanların amellerinin (iyilik ve kötülüklerinin) tartılacağı manevi teraziye ne ad verilir?", options: ["Sırat", "Mizan", "Kevser", "Araf"], answerIndex: 1 },
{ question: "Kur'an-ı Kerim'in baştan sona okunup bitirilmesine ne ad verilir?", options: ["Tilavet", "Kıraat", "Hatim", "Tertil"], answerIndex: 2 },
{ question: "Kur'an-ı Kerim'i güzel sesle, kurallarına uygun olarak ve tecvidli okuma ilmine ne ad verilir?", options: ["Siyer", "Hadis", "Tecvid", "Fıkıh"], answerIndex: 2 },
{ question: "Sünnet olan bir ibadetin bozulması durumunda kaza edilmesi (tekrar yapılması) fıkhen nedir?", options: ["Farz", "Vacip", "Sünnet", "Gerekmez"], answerIndex: 1 },
{ question: "Ramazan ayında güneşin doğmasından (imsak) batmasına (iftar) kadar yeme, içme ve nefsani arzulardan uzak durmaya ne ad verilir?", options: ["İtikaf", "Zekat", "Oruç", "Fidye"], answerIndex: 2 },
{ question: "Kur'an-ı Kerim'in anlaşılması, açıklanması ve yorumlanması ilmine ne ad verilir?", options: ["Tefsir", "Kelam", "Siyer", "Akaid"], answerIndex: 0 },
{ question: "Kur'an-ı Kerim'de her ayetinde 'Allah' lafzı geçen sure hangisidir?", options: ["Yasin Suresi", "Mülk Suresi", "Mücadele Suresi", "Kevser Suresi"], answerIndex: 2 },
{ question: "Kabe'yi inşa eden peygamberler kimlerdir?", options: ["Hz. Adem ve Hz. Şit", "Hz. İbrahim ve Hz. İsmail", "Hz. Davud ve Hz. Süleyman", "Hz. Musa ve Hz. Harun"], answerIndex: 1 },
{ question: "Kur'an'da övülen 'Ashab-ı Kehf' (Mağara Arkadaşları) mağarada kaç yıl uyumuşlardır?", options: ["100", "250", "309", "400"], answerIndex: 2 },
{ question: "Bismillahirrahmânirrahîm ayetinin tam olarak yer aldığı, Fatiha dışında Kur'an'daki tek sure hangisidir?", options: ["Neml Suresi", "Bakara Suresi", "İhlas Suresi", "Yunus Suresi"], answerIndex: 0 },
{ question: "Kur'an-ı Kerim'de geçen 'Kıssaların en güzeli' (Ahsenü'l-Kasas) hangi peygamberin hayatını anlatır?", options: ["Hz. İbrahim", "Hz. Yusuf", "Hz. Muhammed", "Hz. Nuh"], answerIndex: 1 },
{ question: "Kur'an'da kendisinden 'Zünnun' (Balık sahibi) olarak bahsedilen peygamber kimdir?", options: ["Hz. Musa", "Hz. Yunus", "Hz. İsa", "Hz. Yakup"], answerIndex: 1 },
{ question: "Allah'ın emir ve yasaklarını peygamberlerine bildirmesine ne ad verilir?", options: ["İlham", "Vahiy", "Sünnet", "Mucize"], answerIndex: 1 },
{ question: "Peygamber Efendimizin (s.a.v) doğduğu aya ne ad verilir?", options: ["Muharrem", "Ramazan", "Rebiülevvel", "Recep"], answerIndex: 2 },
{ question: "Peygamberimizin annesi Amine vefat ettiğinde o nereye defnedilmiştir?", options: ["Mekke", "Medine", "Taif", "Ebva"], answerIndex: 3 },
{ question: "İlk vahiy geldiğinde Peygamberimizi teselli eden eşi Hz. Hatice'nin ona söylediği meşhur sözün özü nedir?", options: ["Sen hep kazanırsın.", "Allah seni asla utandırmaz.", "Kavmin seni dinleyecektir.", "Mekke'yi terk etmeliyiz."], answerIndex: 1 },
{ question: "Peygamberimizin Medine'ye hicretinden sonra muhacir ve ensar arasında kurduğu kardeşlik bağına ne ad verilir?", options: ["Muahat", "Hılful Fudul", "Darun Nedve", "Biat"], answerIndex: 0 },
{ question: "Bedir Savaşı'nda müşrik ordusunun başkomutanı kimdi?", options: ["Ebu Süfyan", "Ebu Leheb", "Ebu Cehil", "Ümeyye bin Halef"], answerIndex: 2 },
{ question: "Hudeybiye Antlaşması'nı Müslümanlar adına kağıda yazan sahabe kimdir?", options: ["Hz. Ömer", "Hz. Osman", "Hz. Ali", "Hz. Ebubekir"], answerIndex: 2 },
{ question: "Namazda Fatiha suresinden sonra Kur'an'dan bir miktar daha okumaya ne ad verilir?", options: ["Tesbihat", "Kıyam", "Zamm-ı Sure", "Kıraat"], answerIndex: 2 },
{ question: "Kamet ile Ezan arasındaki en belirgin fark nedir?", options: ["Kametin sessiz okunması", "Kamette 'Kad kâmeti's-salâh' cümlesinin bulunması", "Ezanın daha kısa olması", "Kamette tekbir olmaması"], answerIndex: 1 },
{ question: "Güneşin doğmasından yaklaşık 45 dakika sonra başlayıp öğle vaktine kadar kılınabilen nafile namaza ne ad verilir?", options: ["Teheccüd", "Evvabin", "Kuşluk (Duha)", "İşrak"], answerIndex: 2 },
{ question: "Oruçlu iken unutarak yiyip içmek orucu bozar mı?", options: ["Bozar, kaza gerekir", "Bozar, keffaret gerekir", "Bozmaz, oruca devam edilir", "Sadece su içilirse bozmaz"], answerIndex: 2 },
{ question: "Zekat vermekle yükümlü olmak için gereken zenginlik ölçüsüne ulaşan malın üzerinden ne kadar zaman geçmelidir?", options: ["1 Ay", "6 Ay", "1 Kameri Yıl", "3 Yıl"], answerIndex: 2 },
{ question: "Fıtır sadakasının (Fitre) en geç ne zamana kadar verilmesi gerekir?", options: ["Ramazan ayının 15'ine kadar", "Kadir Gecesinde", "Bayram namazından önce", "Bayramın 3. günü"], answerIndex: 2 },
{ question: "Hz. Ebubekir'e 'Sıddık' lakabı hangi olaydan sonra verilmiştir?", options: ["Hicret", "Miraç Hadisesi", "Bedir Savaşı", "Mekke'nin Fethi"], answerIndex: 1 },
{ question: "Hz. Ali döneminde başkent Medine'den hangi şehre taşınmıştır?", options: ["Kufe", "Şam", "Bağdat", "Kahire"], answerIndex: 0 },
{ question: "Peygamberimizin şairlerinden olan ve şiirleriyle müşriklere karşı İslam'ı savunan sahabe kimdir?", options: ["Hassan bin Sabit", "Abdullah bin Revaha", "Ka'b bin Malik", "Zeyd bin Sabit"], answerIndex: 0 },
{ question: "Tebük Seferi'nde ordunun donatılması için tüm malvarlığını bağışlayan sahabe kimdir?", options: ["Hz. Ömer", "Hz. Osman", "Hz. Ebubekir", "Abdurrahman bin Avf"], answerIndex: 2 },
{ question: "Peygamber Efendimizin kabrine defnedildiği sırada kabre inen sahabelerden biri kimdir?", options: ["Hz. Ömer", "Hz. Ali", "Hz. Ebubekir", "Hz. Osman"], answerIndex: 1 },
{ question: "Uhud Savaşı'nda Peygamberimizin etrafında etten duvar örüp ona kalkan olan meşhur kadın sahabe kimdir?", options: ["Nesibe bint Ka'b", "Hz. Aişe", "Hz. Fatıma", "Hz. Sümeyye"], answerIndex: 0 },
{ question: "Kabe'yi onaran müşrikler, Hacerü'l-Esved taşını yerine koyma konusunda anlaşmazlığa düştüklerinde kimi hakem tayin etmişlerdir?", options: ["Ebu Talip", "Hz. Ebubekir", "Hz. Muhammed (s.a.v)", "Ebu Cehil"], answerIndex: 2 },
{ question: "Müslümanların Medine'deki ilk eğitim kurumu olarak bilinen ve Mescid-i Nebevi'nin bitişiğindeki mekana ne ad verilir?", options: ["Darun Nedve", "Suffe", "Mescid-i Aksa", "Darul Erkam"], answerIndex: 1 },
{ question: "Bedir Savaşı'nda esir alınan müşriklerin serbest kalma şartı neydi?", options: ["10 Müslümana okuma yazma öğretmek", "Müslüman olmak", "Mekke'yi terk etmek", "Fidye vermek"], answerIndex: 0 },
{ question: "İslam'da kasten adam öldürmenin kısas dışında affedilmesi durumunda ödenen tazminata ne ad verilir?", options: ["Diyet", "Keffaret", "Fidye", "Zekat"], answerIndex: 0 },
{ question: "İslam miras hukukuna göre vasiyet edilen mal, tüm mirasın en fazla ne kadarı olabilir?", options: ["Tamamı", "Yarısı (1/2)", "Üçte biri (1/3)", "Dörtte biri (1/4)"], answerIndex: 2 },
{ question: "Abdest alırken kıbleye dönmek abdestin nesidir?", options: ["Farzı", "Vacibi", "Sünneti / Adabı", "Mekruhu"], answerIndex: 2 },
{ question: "Namazda Zamm-ı Sure'yi okumayı unutmak hangi secdeyi gerektirir?", options: ["Tilavet Secdesi", "Şükür Secdesi", "Sehiv Secdesi", "Sema Secdesi"], answerIndex: 2 },
{ question: "Hac ve umre niyetiyle ihrama giren kişinin söylemesi sünnet olan Lebbeyk diye başlayan duaya ne ad verilir?", options: ["Teşrik", "Telbiye", "Tahmid", "Salavat"], answerIndex: 1 },
{ question: "Cennetteki kapılardan biri olan ve sadece oruçluların gireceği kapının adı nedir?", options: ["Firdevs", "Reyyan", "Naim", "Adn"], answerIndex: 1 },
{ question: "Kur'an'da kendisine 'Ruhul Kudüs' de denilen ve vahiy getiren melek kimdir?", options: ["Mikail", "İsrafil", "Azrail", "Cebrail"], answerIndex: 3 },
{ question: "İslam inancına göre öldükten sonra yeniden dirilmeye ne ad verilir?", options: ["Haşr", "Ba's", "Mizan", "Berzah"], answerIndex: 1 },
{ question: "Peygamber Efendimiz zamanında yaşamış, Müslüman olmuş fakat Peygamberimizi hiç görememiş nesle ne ad verilir?", options: ["Tabiin", "Tebe-i Tabiin", "Muhadram", "Sahabe"], answerIndex: 2 },
{ question: "Kur'an-ı Kerim'in en kısa suresi olan ve 'Bol nimet' anlamına gelen sure hangisidir?", options: ["İhlas", "Kevser", "Asr", "Nas"], answerIndex: 1 },
{ question: "Peygamberimizin eşlerinden hangisi müminlerin annesi olmasının yanı sıra, ilk İslam halifesinin kızıdır?", options: ["Hz. Hafsa", "Hz. Hatice", "Hz. Aişe", "Hz. Ümmü Seleme"], answerIndex: 2 },
{ question: "Peygamber Efendimiz doğmadan önce Medine'nin yerlilerinden olan iki büyük Arap kabilesi hangileridir?", options: ["Kureyş ve Kinane", "Evs ve Hazrec", "Gatafan ve Süleym", "Hevazin ve Sakif"], answerIndex: 1 },
{ question: "Hudeybiye Antlaşması'nda müşrikleri temsil eden ve daha sonra Müslüman olan elçi kimdir?", options: ["Ebu Süfyan", "Amr bin As", "Süheyl bin Amr", "Halid bin Velid"], answerIndex: 2 },
{ question: "İlk cuma namazı hicret yolculuğu sırasında nerede kılınmıştır?", options: ["Ranuna Vadisi'nde", "Kuba Mescidi'nde", "Sevr Mağarası'nda", "Mescid-i Nebevi'de"], answerIndex: 0 },
{ question: "İslam dininde temizliğe verilen genel isim nedir?", options: ["Necaset", "Taharet", "Gusül", "İstinca"], answerIndex: 1 },
{ question: "Namazda ayaktayken secde edilecek yere bakmak namazın nesidir?", options: ["Farzı", "Sünneti", "Mekruhu", "Vacibi"], answerIndex: 1 },
{ question: "Cuma namazının kılındığı gün, öğle namazı da kılınır mı?", options: ["Kılınır", "Cuma namazı öğle namazı yerine geçer", "Sadece sünneti kılınır", "Tercihe bağlıdır"], answerIndex: 1 },
{ question: "Peygamberimizin hicretten sonra Medine'de yaptırdığı ilk nüfus sayımında yaklaşık kaç Müslüman tespit edilmiştir?", options: ["500", "1500", "3000", "5000"], answerIndex: 1 },
{ question: "Cennete ilk girecek olan peygamber kimdir?", options: ["Hz. Adem", "Hz. İbrahim", "Hz. Musa", "Hz. Muhammed (s.a.v)"], answerIndex: 3 },
{ question: "Müslümanların dinlerini öğrenmek, ibadet etmek ve sosyalleşmek için toplandıkları Mescid-i Nebevi içindeki gölgeliğe ne denir?", options: ["Suffe", "Mihrap", "Minber", "Kürsü"], answerIndex: 0 },
{ question: "Kur'an'da 'Andolsun ki Resulullah'ta sizin için güzel bir örnek vardır' (Üsve-i Hasene) ayetiyle kastedilen peygamber özelliği nedir?", options: ["Cesareti", "Rol model olması", "Adaleti", "Cömertliği"], answerIndex: 1 },
{ question: "Hangi halife döneminde devlet teşkilatlanması yapılarak divan kurulmuş ve hicri takvim kabul edilmiştir?", options: ["Hz. Ebubekir", "Hz. Ömer", "Hz. Osman", "Hz. Ali"], answerIndex: 1 }

];